//! Turn planned toolpaths into G-code.
//!
//! Extrusion math: the deposited bead is a **stadium** (flat core, semicircular
//! shoulders — see `config::bead_area_mm2`), so a move of length `L` advances
//! the filament by `E = L * bead_area / filament_cross_section`. Adjacent beads
//! are *placed* at the stadium spacing by the planner, so the shoulders overlap
//! and surfaces come out watertight without over-extrusion.
//!
//! Output targets Klipper: relative extrusion (`M83`) and a retraction before
//! every travel between separate extrusions. The start/end g-code comes from the
//! printer profile (see `config`); `{placeholders}` are substituted here.

use config::Settings;
use gcode::GcodeBuilder;
use geo2d::{Contour, Point, Polygons};
use rayon::prelude::*;

use crate::plan::{LayerPlan, PathKind, ToolPath, Travel};

/// Emit complete G-code for a planned model.
pub fn to_gcode(layers: &[LayerPlan], s: &Settings) -> String {
    let mut g = GcodeBuilder::new();
    let area = s.filament_area_mm2();
    let travel_f = s.travel_speed_mm_s * 60.0;
    let retract_f = s.retract_speed_mm_s * 60.0;
    // Hopped travels lift by this much. With brick layering, force at least enough
    // to clear a lifted bead (top = layer Z + layer height) even if z-hop is off.
    let hop_mm = if s.brick_layers {
        s.z_hop_mm.max(s.layer_height_mm + 0.25)
    } else {
        s.z_hop_mm
    };

    // Cumulative time after each layer — drives M73 progress/remaining.
    let mut cum_secs: Vec<f64> = Vec::with_capacity(layers.len());
    {
        let travel_v = s.travel_speed_mm_s.max(1.0);
        let mut acc = 0.0;
        let mut prev_z = 0.0;
        for layer in layers {
            acc += (layer.print_z_mm - prev_z).abs() / travel_v;
            prev_z = layer.print_z_mm;
            acc += layer_print_seconds(layer, s, layer.speed_scale);
            cum_secs.push(acc);
        }
    }
    let total_secs = cum_secs.last().copied().unwrap_or(0.0);
    let (fil_mm, fil_g) = estimate_filament(layers, s);

    g.comment("generated by slicer");
    g.comment(&format!("estimated printing time = {}", format_duration(total_secs)));
    g.comment(&format!("filament used [mm] = {fil_mm:.1}"));
    g.comment(&format!("filament used [g] = {fil_g:.1}"));
    g.comment(&format!("total layers = {}", layers.len()));
    if s.max_volumetric_speed_mm3_s > 0.0 {
        g.comment(&format!("flow limit = {:.1} mm3/s", s.max_volumetric_speed_mm3_s));
        for (kind, nominal, clamped) in audit_flow_clamps(layers, s) {
            g.comment(&format!(
                "flow-limited: {} {:.0} -> {:.0} mm/s",
                kind_label(kind),
                nominal,
                clamped
            ));
        }
    }
    if s.temp_shaping {
        for z in audit_temp_shaping(layers, s) {
            g.comment(&format!(
                "temp shaping: layers {}-{} -> {:.0}C",
                z.first_layer, z.last_layer, z.temp_c
            ));
        }
    }
    if s.thermal_governor {
        for r in audit_governor(layers, s) {
            g.comment(&format!(
                "thermal governor: layers {}-{} slowed to {:.0}%{}",
                r.first_layer,
                r.last_layer,
                r.worst_scale * 100.0,
                if r.floor_hit { " (still hot at the min-speed floor)" } else { "" }
            ));
        }
    }
    g.comment(&format!(
        "layer_h={} line_w={} walls={} top/bot={}/{} infill={} ({}) bed={}x{}",
        s.layer_height_mm,
        s.line_width_mm,
        s.wall_count,
        s.top_layers,
        s.bottom_layers,
        s.infill_density,
        s.sparse_pattern.label(),
        s.bed_size_x_mm,
        s.bed_size_y_mm
    ));

    // Machine state we depend on, then the printer's start sequence (heating /
    // homing / PRINT_START macro).
    g.raw("G21"); // millimeters
    g.raw("G90"); // absolute XYZ
    g.raw("M83"); // relative extrusion (Klipper-recommended)
    emit_template(&mut g, &s.start_gcode, s);
    // Motion limits, set after PRINT_START so our values win. M204 S is understood
    // by Klipper and Marlin; SQUARE_CORNER_VELOCITY is Klipper's "jerk" equivalent.
    // Acceleration then follows the feature being printed (M204 per change).
    let mut cur_accel = s.first_layer_accel_mm_s2;
    g.raw(&format!("M204 S{cur_accel:.0}"));
    g.raw(&format!("SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY={:.1}", s.jerk_mm_s));
    if s.pressure_advance > 0.0 {
        g.raw(&format!("SET_PRESSURE_ADVANCE ADVANCE={:.4}", s.pressure_advance));
    }
    g.fan(0);
    let mut cur_fan = 0u32;

    let fan_duty = |frac: f64| (frac.clamp(0.0, 1.0) * 255.0).round() as u32;
    // Extra fans, gated on the printer declaring them — vanilla Klipper/Marlin
    // reads the M106 P-form as the primary fan. The aux part fan (M106 P2)
    // follows the part fan's first-layers gate in the loop below; the chamber
    // exhaust (M106 P3) runs flat for the whole print. Both shut off at the end.
    let mut cur_aux_fan = 0u32;
    if s.has_aux_fan {
        g.raw("M106 P2 S0");
    }
    if s.has_exhaust_fan && s.exhaust_fan_speed > 0.0 {
        g.raw(&format!("M106 P3 S{}", fan_duty(s.exhaust_fan_speed)));
    }
    let first_spiral = s.bottom_layers; // vase mode: first continuously-rising layer
    // Tail of the most recently printed path, for wiping the nozzle back over
    // it when the next travel retracts. Carried across layers: a layer-change
    // wipe runs one layer height above the bead, which still releases the
    // pressure while moving instead of parked on the seam.
    let mut wipe_tail: Option<Vec<Point>> = None;

    for layer in layers {
        g.comment(&format!("LAYER {} z={:.3}", layer.index, layer.print_z_mm));
        // Time-based progress for the printer's display.
        let done = if layer.index == 0 { 0.0 } else { cum_secs[layer.index - 1] };
        if total_secs > 0.0 {
            g.raw(&format!(
                "M73 P{:.0} R{:.0}",
                (done / total_secs * 100.0).min(100.0),
                ((total_secs - done) / 60.0).ceil()
            ));
        }
        // Temperature: shaping's scheduled setpoints win; otherwise the
        // one-shot drop from first-layer temp to printing temp. M104 either
        // way — set without waiting, the schedule already planned the leads.
        if let Some(t) = layer.temp_command_c {
            g.raw(&format!("M104 S{t:.0}"));
        } else if layer.index == 1 && s.first_layer_nozzle_temp_c != s.nozzle_temp_c {
            g.raw(&format!("M104 S{}", s.nozzle_temp_c));
        }
        // Part cooling: off for the first `fan_off_layers`, then the normal duty;
        // bridges may override per path below.
        let normal_fan = if layer.index < s.fan_off_layers { 0 } else { fan_duty(s.fan_speed) };
        if normal_fan != cur_fan {
            g.fan(normal_fan);
            cur_fan = normal_fan;
        }
        if s.has_aux_fan {
            let aux = if layer.index < s.fan_off_layers { 0 } else { fan_duty(s.aux_fan_speed) };
            if aux != cur_aux_fan {
                g.raw(&format!("M106 P2 S{aux}"));
                cur_aux_fan = aux;
            }
        }

        // Spiral vase: above the solid bottom, the single wall loop climbs
        // continuously from the previous layer's top to this one's.
        if s.spiral_vase && layer.index >= first_spiral {
            if let Some(path) = spiral_loop(layer) {
                let feed = feed_for(path, layer.index, layer.height_mm, layer_flow_cap_mm3_s(layer, s), s)
                    * layer.speed_scale;
                let coeff = config::bead_area_mm2(path.width_mm, layer.height_mm * path.height_scale) / area
                    * flow_factor(path, s);
                g.raw(&format!(";TYPE:{}", type_label(path.kind)));
                let accel = accel_for(path.kind, layer.index, s);
                if (accel - cur_accel).abs() > 0.5 {
                    g.raw(&format!("M204 S{accel:.0}"));
                    cur_accel = accel;
                }
                emit_spiral_layer(&mut g, layer, path, coeff, feed, travel_f, retract_f, s);
                continue;
            }
        }

        g.move_z(layer.print_z_mm, travel_f);
        let mut cur_z = layer.print_z_mm;

        let mut cur_type: Option<&'static str> = None;
        for (i, path) in layer.paths.iter().enumerate() {
            if path.points.len() < 2 {
                continue;
            }
            // Feature annotation + acceleration, on change. The accel is set
            // before the lead-in travel so the whole block moves as one.
            let t = type_label(path.kind);
            if cur_type != Some(t) {
                g.raw(&format!(";TYPE:{t}"));
                cur_type = Some(t);
            }
            let accel = accel_for(path.kind, layer.index, s);
            if (accel - cur_accel).abs() > 0.5 {
                g.raw(&format!("M204 S{accel:.0}"));
                cur_accel = accel;
            }
            // Bridges and overhanging walls want max cooling; everything else
            // the layer's normal duty.
            let airborne = matches!(
                path.kind,
                PathKind::Bridge | PathKind::ArcOverhang | PathKind::InternalBridge | PathKind::OverhangWall
            );
            let want_fan = if airborne && layer.index >= s.fan_off_layers {
                fan_duty(s.bridge_fan_speed).max(normal_fan)
            } else {
                normal_fan
            };
            if want_fan != cur_fan {
                g.fan(want_fan);
                cur_fan = want_fan;
            }

            // Brick-layered perimeters print half a layer up and over-extrude a touch.
            let z = layer.print_z_mm + path.z_offset_mm;
            let feed =
                feed_for(path, layer.index, layer.height_mm, layer_flow_cap_mm3_s(layer, s), s)
                    * layer.speed_scale
                    * path_scale(layer, i);
            let coeff = config::bead_area_mm2(path.width_mm, layer.height_mm * path.height_scale) / area
                * flow_factor(path, s);
            let start = path.points[0];

            // The travel (combed route, or a retracted/z-hopped hop over a void)
            // was planned in `plan_travels` — replay it, at this path's Z.
            let tr = &layer.travels[i];
            if tr.retract && s.retract_len_mm > 0.0 {
                g.retract(s.retract_len_mm, retract_f);
                // Wipe back along the printed bead: the pressure-release ooze
                // smears onto plastic instead of blobbing the seam.
                if s.wipe_mm > 0.0 {
                    if let Some(tail) = &wipe_tail {
                        for p in tail {
                            g.travel(p.x_mm(), p.y_mm(), travel_f);
                        }
                    }
                }
            }
            if tr.hop && hop_mm > 0.0 {
                g.move_z(z + hop_mm, travel_f);
            } else if (z - cur_z).abs() > 1.0e-9 {
                g.move_z(z, travel_f);
            }
            for pt in &tr.points {
                g.travel(pt.x_mm(), pt.y_mm(), travel_f);
            }
            if tr.hop && hop_mm > 0.0 {
                g.move_z(z, travel_f);
            }
            cur_z = z;
            if tr.retract && s.retract_len_mm > 0.0 {
                g.unretract(s.retract_len_mm, retract_f);
            }

            if let Some(ws) = &path.widths {
                // Variable-width bead: per-segment E from the mean of the two
                // endpoint widths (no arc fitting — E varies along the path).
                let n_pts = path.points.len();
                let segs = if path.closed { n_pts } else { n_pts - 1 };
                for k in 0..segs {
                    let a = path.points[k];
                    let b = path.points[(k + 1) % n_pts];
                    let w = 0.5 * (ws[k] + ws[(k + 1) % n_pts]);
                    let c = config::bead_area_mm2(w, layer.height_mm * path.height_scale) / area
                        * flow_factor(path, s);
                    g.extrude(b.x_mm(), b.y_mm(), dist_mm(a, b) * c, feed);
                }
            } else if s.arc_fitting {
                emit_arcs(&mut g, &path.points, path.closed, coeff, feed, s.arc_tolerance_mm);
            } else {
                let mut prev = start;
                for &p in &path.points[1..] {
                    g.extrude(p.x_mm(), p.y_mm(), dist_mm(prev, p) * coeff, feed);
                    prev = p;
                }
                if path.closed {
                    g.extrude(start.x_mm(), start.y_mm(), dist_mm(prev, start) * coeff, feed);
                }
            }
            wipe_tail = compute_wipe_tail(path, s.wipe_mm);
        }
    }

    if s.retract_len_mm > 0.0 {
        g.retract(s.retract_len_mm, retract_f);
    }
    if total_secs > 0.0 {
        g.raw("M73 P100 R0");
    }
    // Leave no P-addressed fan running: end g-code macros handle the primary
    // fan (M107) but don't know about these.
    if cur_aux_fan != 0 {
        g.raw("M106 P2 S0");
    }
    if s.has_exhaust_fan && s.exhaust_fan_speed > 0.0 {
        g.raw("M106 P3 S0");
    }
    emit_template(&mut g, &s.end_gcode, s);

    g.finish()
}

/// The single closed external-perimeter loop of a vase layer, if the layer is
/// spiralable (exactly one printable path of that shape).
fn spiral_loop(layer: &LayerPlan) -> Option<&ToolPath> {
    let mut it = layer.paths.iter().filter(|p| p.points.len() >= 2);
    match (it.next(), it.next()) {
        (Some(p), None) if p.closed && p.kind == PathKind::ExternalPerimeter => Some(p),
        _ => None,
    }
}

/// Print one vase layer: walk the loop once, ramping Z linearly with the
/// distance traveled so the wall rises in one continuous helix (no seam, no
/// layer-change retraction).
#[allow(clippy::too_many_arguments)]
fn emit_spiral_layer(
    g: &mut GcodeBuilder,
    layer: &LayerPlan,
    path: &ToolPath,
    coeff: f64,
    feed: f64,
    travel_f: f64,
    retract_f: f64,
    s: &Settings,
) {
    let z_top = layer.print_z_mm;
    let z_bot = z_top - layer.height_mm;
    // Reach the loop start (real travel only on the first spiral layer — after
    // that the nozzle is already at the loop's start/end point).
    if let Some(tr) = layer.travels.first() {
        if !tr.points.is_empty() {
            if tr.retract && s.retract_len_mm > 0.0 {
                g.retract(s.retract_len_mm, retract_f);
            }
            for pt in &tr.points {
                g.travel(pt.x_mm(), pt.y_mm(), travel_f);
            }
            if tr.retract && s.retract_len_mm > 0.0 {
                g.unretract(s.retract_len_mm, retract_f);
            }
        }
    }
    let pts = &path.points;
    let n = pts.len();
    let total: f64 = (0..n).map(|k| dist_mm(pts[k], pts[(k + 1) % n])).sum();
    if total < 1.0e-6 {
        return;
    }
    let mut cum = 0.0;
    for k in 1..=n {
        let a = pts[k - 1];
        let b = pts[k % n];
        let d = dist_mm(a, b);
        if d < 1.0e-9 {
            continue;
        }
        cum += d;
        let z = z_bot + (z_top - z_bot) * (cum / total);
        g.extrude_z(b.x_mm(), b.y_mm(), z, d * coeff, feed);
    }
}

/// Substitute `{placeholders}` in a template and emit it line by line.
fn emit_template(g: &mut GcodeBuilder, template: &str, s: &Settings) {
    let text = substitute(template, s);
    for line in text.lines() {
        if !line.trim().is_empty() {
            g.raw(line.trim_end());
        }
    }
}

fn substitute(template: &str, s: &Settings) -> String {
    template
        .replace("{nozzle_temp}", &s.nozzle_temp_c.to_string())
        .replace("{first_layer_nozzle_temp}", &s.first_layer_nozzle_temp_c.to_string())
        .replace("{bed_temp}", &s.bed_temp_c.to_string())
        .replace("{bed_x}", &format!("{:.3}", s.bed_size_x_mm))
        .replace("{bed_y}", &format!("{:.3}", s.bed_size_y_mm))
        .replace("{bed_z}", &format!("{:.3}", s.bed_size_z_mm))
        .replace("{layer_height}", &format!("{:.3}", s.layer_height_mm))
        .replace("{first_layer_height}", &format!("{:.3}", s.first_layer_height_mm))
        .replace("{nozzle_diameter}", &format!("{:.3}", s.nozzle_diameter_mm))
}

/// The configured speed (mm/s) for a feature, before any limits.
fn nominal_speed_mm_s(kind: PathKind, layer_index: usize, s: &Settings) -> f64 {
    if layer_index == 0 {
        return s.first_layer_speed_mm_s; // first layer is slow everywhere
    }
    match kind {
        PathKind::ExternalPerimeter => s.external_perimeter_speed_mm_s,
        PathKind::Solid => s.solid_speed_mm_s,
        PathKind::GapFill => s.gap_fill_speed_mm_s,
        PathKind::Ironing => s.ironing_speed_mm_s,
        PathKind::Support => s.support_speed_mm_s,
        // Bridges print into air anchored on both ends.
        PathKind::Bridge => s.bridge_speed_mm_s,
        // Arc overhangs cantilever sideways off the previous ring while
        // unsupported along their whole length — far more delicate than a
        // bridge: ~30% of bridge speed, held in the 5–15 mm/s window the
        // technique is known to work in.
        PathKind::ArcOverhang => (s.bridge_speed_mm_s * 0.3).clamp(5.0, 15.0),
        // Internal bridges (solid over sparse) are anchored every infill cell:
        // the free span is spacing/density, not a real bridge's max span. Sag
        // scales with span, so scale the bridge speed by the span ratio —
        // never slower than a bridge, never faster than solid fill.
        PathKind::InternalBridge => {
            let spacing = config::bead_spacing_mm(s.line_width_mm, s.layer_height_mm);
            let cell = if s.infill_density > 0.0 { spacing / s.infill_density } else { f64::MAX };
            let ratio = (s.max_bridge_span_mm / cell).max(1.0);
            (s.bridge_speed_mm_s * ratio).min(s.solid_speed_mm_s)
        }
        // Wall stretches past the layer below: same physics as bridges.
        PathKind::OverhangWall => s.overhang_speed_mm_s,
        // Skirt is layer-0 only (handled above); listed for exhaustiveness.
        PathKind::Skirt | PathKind::Perimeter | PathKind::Infill => s.print_speed_mm_s,
    }
}

/// Extrusion-flow factor for a path beyond its w×h geometry: per-path flow
/// (brick, ironing), per-kind flow (bridges), and the global multiplier.
fn flow_factor(path: &ToolPath, s: &Settings) -> f64 {
    let kind_flow = if matches!(path.kind, PathKind::Bridge | PathKind::ArcOverhang) { s.bridge_flow } else { 1.0 };
    path.flow * kind_flow * s.extrusion_multiplier
}

/// The nozzle temperature planned for a layer: temperature shaping's schedule
/// when present, else the first-layer / profile temperature.
fn layer_nozzle_c(layer: &LayerPlan, s: &Settings) -> f64 {
    layer.planned_temp_c.unwrap_or(if layer.index == 0 {
        s.first_layer_nozzle_temp_c as f64
    } else {
        s.nozzle_temp_c as f64
    })
}

/// The melt ceiling in force on a layer (mm³/s; 0 = unlimited): the profile
/// cap at the profile temperature, derated linearly when temperature shaping
/// runs the layer cooler. Never raised on warmer layers — the profile cap is
/// the calibrated number.
fn layer_flow_cap_mm3_s(layer: &LayerPlan, s: &Settings) -> f64 {
    let cap = s.max_volumetric_speed_mm3_s;
    if cap <= 0.0 {
        return 0.0;
    }
    let below = s.nozzle_temp_c as f64 - layer_nozzle_c(layer, s);
    if below > 0.0 {
        (cap - s.max_flow_derate_per_c.max(0.0) * below).max(1.0)
    } else {
        cap
    }
}

/// Feed rate (mm/min) for a path: the per-feature speed, clamped so the
/// volumetric flow `width × height × speed × flow` never exceeds the layer's
/// melt-rate ceiling (`flow_cap_mm3_s`, 0 = unlimited — pass
/// `layer_flow_cap_mm3_s` so temperature shaping's derate applies). One
/// function feeds the g-code, the time estimate, and the min-layer-time pass,
/// so they always agree.
fn feed_for(
    path: &ToolPath,
    layer_index: usize,
    layer_height_mm: f64,
    flow_cap_mm3_s: f64,
    s: &Settings,
) -> f64 {
    let mut v = nominal_speed_mm_s(path.kind, layer_index, s);
    if flow_cap_mm3_s > 0.0 {
        let mm3_per_mm =
            config::bead_area_mm2(path.width_mm, layer_height_mm * path.height_scale) * flow_factor(path, s);
        if mm3_per_mm > 1.0e-9 {
            v = v.min(flow_cap_mm3_s / mm3_per_mm);
        }
    }
    v * 60.0
}

/// Where the flow ceiling bites: per feature kind (skipping the first layer),
/// the nominal speed and the worst (slowest) clamped speed, for kinds where
/// the clamp actually engaged. Drives the loud reporting in the g-code
/// header, the CLI summary, and the GUI status line.
pub fn audit_flow_clamps(layers: &[LayerPlan], s: &Settings) -> Vec<(PathKind, f64, f64)> {
    use std::collections::BTreeMap;
    let mut worst: BTreeMap<&'static str, (PathKind, f64, f64)> = BTreeMap::new();
    for layer in layers {
        if layer.index == 0 {
            continue; // first layer is slowed anyway
        }
        for path in &layer.paths {
            if path.points.len() < 2 {
                continue;
            }
            let nominal = nominal_speed_mm_s(path.kind, layer.index, s);
            let clamped = feed_for(path, layer.index, layer.height_mm, layer_flow_cap_mm3_s(layer, s), s) / 60.0;
            if clamped < nominal - 1.0e-6 {
                worst
                    .entry(kind_label(path.kind))
                    .and_modify(|e| e.2 = e.2.min(clamped))
                    .or_insert((path.kind, nominal, clamped));
            }
        }
    }
    worst.into_values().collect()
}

/// Human-readable feature name for a path kind — used in g-code header
/// comments, the CLI flow report, and the GUI's flow-limit table.
pub fn kind_label(kind: PathKind) -> &'static str {
    match kind {
        PathKind::Skirt => "skirt",
        PathKind::ExternalPerimeter => "outer wall",
        PathKind::Perimeter => "inner wall",
        PathKind::OverhangWall => "overhang wall",
        PathKind::Solid => "solid",
        PathKind::Infill => "infill",
        PathKind::GapFill => "gap fill",
        PathKind::Ironing => "ironing",
        PathKind::Support => "support",
        PathKind::Bridge => "bridge",
        PathKind::InternalBridge => "internal bridge",
        PathKind::ArcOverhang => "arc overhang",
    }
}

/// `;TYPE:` annotation per feature, in the names g-code viewers (Mainsail,
/// Fluidd, OrcaSlicer's own) already colour-code.
fn type_label(kind: PathKind) -> &'static str {
    match kind {
        PathKind::Skirt => "Skirt",
        PathKind::ExternalPerimeter => "Outer wall",
        PathKind::Perimeter => "Inner wall",
        PathKind::OverhangWall => "Overhang wall",
        PathKind::Solid => "Solid infill",
        PathKind::Infill => "Sparse infill",
        PathKind::GapFill => "Gap infill",
        PathKind::Ironing => "Ironing",
        PathKind::Support => "Support",
        // Arc overhangs report as Bridge: viewers colour-code known names.
        PathKind::Bridge | PathKind::ArcOverhang => "Bridge",
        PathKind::InternalBridge => "Internal Bridge",
    }
}

/// Acceleration (mm/s²) for a feature: gentle on the first layer (adhesion)
/// and the visible outer wall (ringing); everything else at the main limit.
/// Used for both the emitted M204s and the time estimate.
fn accel_for(kind: PathKind, layer_index: usize, s: &Settings) -> f64 {
    if layer_index == 0 {
        return s.first_layer_accel_mm_s2;
    }
    match kind {
        PathKind::ExternalPerimeter | PathKind::OverhangWall => s.outer_wall_accel_mm_s2,
        _ => s.acceleration_mm_s2,
    }
}

fn dist_mm(a: Point, b: Point) -> f64 {
    let dx = a.x_mm() - b.x_mm();
    let dy = a.y_mm() - b.y_mm();
    (dx * dx + dy * dy).sqrt()
}

/// The vertices to wipe back over after finishing `path`: walking backwards
/// from its end (the seam, for closed loops) over at most `wipe_mm` — capped
/// at half the path so short strokes don't fully retrace.
fn compute_wipe_tail(path: &ToolPath, wipe_mm: f64) -> Option<Vec<Point>> {
    let pts = &path.points;
    let n = pts.len();
    if wipe_mm <= 0.0 || n < 2 {
        return None;
    }
    let mut total: f64 = pts.windows(2).map(|w| dist_mm(w[0], w[1])).sum();
    if path.closed {
        total += dist_mm(pts[n - 1], pts[0]);
    }
    let budget = wipe_mm.min(total * 0.5);
    // Predecessors of the end point: a closed loop ends back at pts[0], an
    // open path at pts[n-1].
    let mut cur = if path.closed { pts[0] } else { pts[n - 1] };
    let idxs: Box<dyn Iterator<Item = usize>> =
        if path.closed { Box::new((1..n).rev()) } else { Box::new((0..n - 1).rev()) };
    let mut tail = Vec::new();
    let mut acc = 0.0;
    for j in idxs {
        let p = pts[j];
        let d = dist_mm(cur, p);
        if acc + d >= budget {
            let t = ((budget - acc) / d.max(1.0e-9)).clamp(0.0, 1.0);
            tail.push(Point::from_mm(
                cur.x_mm() + (p.x_mm() - cur.x_mm()) * t,
                cur.y_mm() + (p.y_mm() - cur.y_mm()) * t,
            ));
            break;
        }
        tail.push(p);
        acc += d;
        cur = p;
    }
    (!tail.is_empty()).then_some(tail)
}

/// Need at least this many points to bother emitting an arc (avoids fitting corners).
const ARC_MIN_PTS: usize = 4;
/// Above this radius (mm) a run is treated as straight, not an arc.
const ARC_MAX_R: f64 = 1000.0;

/// Emit a path's extrusion, replacing runs of points that lie on a circular arc
/// with a single G2/G3 and leaving the rest as G1 segments.
fn emit_arcs(g: &mut GcodeBuilder, points: &[Point], closed: bool, coeff: f64, feed: f64, tol: f64) {
    let mut pts: Vec<(f64, f64)> = points.iter().map(|p| (p.x_mm(), p.y_mm())).collect();
    if closed {
        pts.push(pts[0]); // walk the closing segment too
    }
    let n = pts.len();
    let mut i = 0;
    while i + 1 < n {
        match fit_arc(&pts, i, tol) {
            Some((j, cx, cy, cw)) => {
                let len = arc_span_len(&pts[i..=j], cx, cy);
                g.arc(cw, pts[j].0, pts[j].1, cx - pts[i].0, cy - pts[i].1, len * coeff, feed);
                i = j;
            }
            None => {
                let (x, y) = pts[i + 1];
                g.extrude(x, y, pdist(pts[i], pts[i + 1]) * coeff, feed);
                i += 1;
            }
        }
    }
}

/// Longest run starting at `i` that lies on one circular arc within `tol`.
/// Returns (end index, center x, center y, clockwise) or None for a straight run.
fn fit_arc(pts: &[(f64, f64)], i: usize, tol: f64) -> Option<(usize, f64, f64, bool)> {
    let n = pts.len();
    if i + 2 >= n {
        return None;
    }
    let (cx, cy) = circumcenter(pts[i], pts[i + 1], pts[i + 2])?;
    let r = pdist(pts[i], (cx, cy));
    if !(1.0e-3..=ARC_MAX_R).contains(&r) {
        return None;
    }
    let cw = turn_cw(pts[i], pts[i + 1], pts[i + 2]);
    // A segment "hugs" the arc when its chord deviates from the circle by ≤ tol
    // (sagitta = r − distance(chord midpoint, center)). This rejects polygons whose
    // vertices happen to be concyclic (e.g. a square's 4 corners) — only a densely
    // sampled curve passes.
    let hugs = |a: (f64, f64), b: (f64, f64)| {
        let m = ((a.0 + b.0) * 0.5, (a.1 + b.1) * 0.5);
        r - pdist(m, (cx, cy)) <= tol
    };
    if !hugs(pts[i], pts[i + 1]) || !hugs(pts[i + 1], pts[i + 2]) {
        return None;
    }
    // The sweep about the center must be monotone (and under a full turn):
    // a path that doubles back along the same circle stays within `tol` and
    // keeps a consistent polyline turn, but the firmware draws only the
    // start→end angular gap — the bead's full length would be squeezed into
    // a short arc as an over-extruded blob (seen on seam-adjacent jitters).
    let sweep = |a: (f64, f64), b: (f64, f64)| -> f64 {
        let v0 = (a.0 - cx, a.1 - cy);
        let v1 = (b.0 - cx, b.1 - cy);
        (v0.0 * v1.1 - v0.1 * v1.0).atan2(v0.0 * v1.0 + v0.1 * v1.1)
    };
    let dir = if cw { -1.0 } else { 1.0 };
    let s0 = sweep(pts[i], pts[i + 1]) * dir;
    let s1 = sweep(pts[i + 1], pts[i + 2]) * dir;
    if s0 <= 0.0 || s1 <= 0.0 {
        return None;
    }
    let mut total = s0 + s1;
    let mut j = i + 2;
    while j + 1 < n {
        let p = pts[j + 1];
        if (pdist(p, (cx, cy)) - r).abs() > tol || turn_cw(pts[j - 1], pts[j], p) != cw || !hugs(pts[j], p) {
            break;
        }
        let ds = sweep(pts[j], p) * dir;
        if ds <= 0.0 || total + ds >= std::f64::consts::TAU - 0.05 {
            break;
        }
        total += ds;
        j += 1;
    }
    if j + 1 - i < ARC_MIN_PTS {
        return None;
    }
    // Refit on the run's endpoints + midpoint so I/J land accurately.
    let (cx, cy) = circumcenter(pts[i], pts[(i + j) / 2], pts[j]).unwrap_or((cx, cy));
    Some((j, cx, cy, cw))
}

fn pdist(a: (f64, f64), b: (f64, f64)) -> f64 {
    (a.0 - b.0).hypot(a.1 - b.1)
}

/// Clockwise turn a→b→c in printer XY (G2 direction).
fn turn_cw(a: (f64, f64), b: (f64, f64), c: (f64, f64)) -> bool {
    (b.0 - a.0) * (c.1 - b.1) - (b.1 - a.1) * (c.0 - b.0) < 0.0
}

/// Center of the circle through three points (None if collinear).
fn circumcenter(a: (f64, f64), b: (f64, f64), c: (f64, f64)) -> Option<(f64, f64)> {
    let d = 2.0 * (a.0 * (b.1 - c.1) + b.0 * (c.1 - a.1) + c.0 * (a.1 - b.1));
    if d.abs() < 1.0e-9 {
        return None;
    }
    let (a2, b2, c2) = (a.0 * a.0 + a.1 * a.1, b.0 * b.0 + b.1 * b.1, c.0 * c.0 + c.1 * c.1);
    let ux = (a2 * (b.1 - c.1) + b2 * (c.1 - a.1) + c2 * (a.1 - b.1)) / d;
    let uy = (a2 * (c.0 - b.0) + b2 * (a.0 - c.0) + c2 * (b.0 - a.0)) / d;
    Some((ux, uy))
}

/// Arc length along a run of points about center (cx, cy): radius × total swept angle.
fn arc_span_len(run: &[(f64, f64)], cx: f64, cy: f64) -> f64 {
    let r = pdist(run[0], (cx, cy));
    let mut ang = 0.0;
    for w in run.windows(2) {
        let v0 = (w[0].0 - cx, w[0].1 - cy);
        let v1 = (w[1].0 - cx, w[1].1 - cy);
        ang += (v0.0 * v1.1 - v0.1 * v1.0).atan2(v0.0 * v1.0 + v0.1 * v1.1).abs();
    }
    r * ang
}

/// Estimate print time (seconds) via a trapezoidal motion simulation:
/// acceleration-limited moves with a jerk-based junction speed limit and
/// look-ahead. Mirrors the move sequence `to_gcode` emits; heating/homing in the
/// start g-code is not counted.
pub fn estimate_seconds(layers: &[LayerPlan], s: &Settings) -> f64 {
    let travel_v = s.travel_speed_mm_s.max(1.0);
    let mut total = 0.0;
    let mut prev_z = 0.0;
    for layer in layers {
        total += (layer.print_z_mm - prev_z).abs() / travel_v;
        prev_z = layer.print_z_mm;
        total += layer_print_seconds(layer, s, layer.speed_scale);
    }
    total
}

/// Extrusion + intra-layer travel time for one layer, at the given speed scale,
/// using the planned travels. Acceleration follows the per-feature M204s the
/// emitter writes, so the estimate tracks what the printer is actually told.
fn layer_print_seconds(layer: &LayerPlan, s: &Settings, scale: f64) -> f64 {
    let travel_v = s.travel_speed_mm_s.max(1.0);
    let retract_t = if s.retract_len_mm > 0.0 {
        2.0 * s.retract_len_mm / s.retract_speed_mm_s.max(1.0)
    } else {
        0.0
    };
    let hop_t = if s.z_hop_mm > 0.0 { 2.0 * s.z_hop_mm / travel_v } else { 0.0 };
    let mut t = 0.0;
    let mut last_pos: Option<Point> = None;
    let mut prev_path_len = 0.0_f64;
    for (i, path) in layer.paths.iter().enumerate() {
        if path.points.len() < 2 {
            continue;
        }
        let accel = accel_for(path.kind, layer.index, s).max(1.0);
        if let Some(tr) = layer.travels.get(i) {
            // Travel length: from the previous position through the route points.
            let mut len = 0.0;
            let mut prev = last_pos;
            for &pt in &tr.points {
                if let Some(p) = prev {
                    len += dist_mm(p, pt);
                }
                prev = Some(pt);
            }
            t += trapezoid_time(len, 0.0, 0.0, travel_v, accel);
            if tr.retract {
                t += retract_t;
                // The wipe back over the previous path before travelling.
                if s.wipe_mm > 0.0 && prev_path_len > 0.0 {
                    t += s.wipe_mm.min(prev_path_len * 0.5) / travel_v;
                }
            }
            if tr.hop {
                t += hop_t;
            }
        }
        t += path_extrusion_seconds(layer, i, s, scale * path_scale(layer, i));
        last_pos = Some(path_end(path));
        prev_path_len = path.points.windows(2).map(|w| dist_mm(w[0], w[1])).sum();
    }
    t
}

/// Plan the lead-in travel for every path: comb a route that stays inside the
/// part when one exists, else retract and z-hop straight over the gap. Stored on
/// each layer so g-code and the GUI preview agree.
///
/// The cross-layer chain state (where the nozzle is when a layer starts) only
/// depends on path endpoints, so it is derived sequentially first — then each
/// layer's travels (including its comb graph, the expensive part) are planned in
/// parallel.
pub(crate) fn plan_travels(plans: &mut [LayerPlan], s: &Settings) {
    // Entry state per layer: nozzle position + z-phase after the previous layer.
    let mut entries: Vec<(Option<Point>, f64)> = Vec::with_capacity(plans.len());
    let mut last_pos: Option<Point> = None;
    let mut last_z_off = 0.0_f64;
    for plan in plans.iter() {
        entries.push((last_pos, last_z_off));
        for path in &plan.paths {
            if path.points.len() >= 2 {
                last_pos = Some(path_end(path));
                last_z_off = path.z_offset_mm;
            }
        }
    }

    plans
        .par_iter_mut()
        .zip(entries)
        .for_each(|(plan, (entry_pos, entry_z_off))| plan_layer_travels(plan, entry_pos, entry_z_off, s));
}

/// Plan one layer's travels, starting from the given entry position/z-phase.
fn plan_layer_travels(plan: &mut LayerPlan, entry_pos: Option<Point>, entry_z_off: f64, s: &Settings) {
    let mut last_pos = entry_pos;
    let mut last_z_off = entry_z_off;
    let mut travels: Vec<Travel> = Vec::with_capacity(plan.paths.len());
    let mut comb: Option<CombGraph> = None;
    for path in &plan.paths {
        if path.points.len() < 2 {
            travels.push(Travel::default());
            continue;
        }
        let start = path.points[0];
        // Brick layering: a travel into or out of a lifted perimeter must hop
        // clear so the nozzle never drags through a bead at the other Z phase.
        let phase_travel =
            s.brick_layers && last_pos.is_some() && (path.z_offset_mm != 0.0 || last_z_off != 0.0);
        let travel = if phase_travel {
            Travel { points: vec![start], retract: s.retract_len_mm > 0.0, hop: true }
        } else {
            match last_pos {
                None => Travel { points: vec![start], retract: false, hop: false },
                Some(prev) => {
                    let crosses = dist_mm(prev, start) >= MIN_TRAVEL_MM
                        && travel_crosses(&plan.outline, prev, start);
                    if !crosses {
                        Travel { points: vec![start], retract: false, hop: false }
                    } else {
                        let graph = comb.get_or_insert_with(|| CombGraph::build(&plan.outline));
                        match graph.route(&plan.outline, prev, start) {
                            Some(route) => Travel { points: route, retract: false, hop: false },
                            None => Travel {
                                points: vec![start],
                                retract: s.retract_len_mm > 0.0,
                                hop: s.z_hop_mm > 0.0,
                            },
                        }
                    }
                }
            }
        };
        last_pos = Some(path_end(path));
        last_z_off = path.z_offset_mm;
        travels.push(travel);
    }
    plan.travels = travels;
}

/// Slow down layers that print faster than `min_layer_time_s` (down to a floor
/// speed) so they have time to cool before the next layer.
pub(crate) fn apply_min_layer_time(plans: &mut [LayerPlan], s: &Settings) {
    if s.min_layer_time_s <= 0.0 {
        return;
    }
    let floor = s.min_print_speed_mm_s / s.print_speed_mm_s.max(1.0);
    plans.par_iter_mut().for_each(|plan| {
        let t = layer_print_seconds(plan, s, 1.0);
        if t > 0.0 && t < s.min_layer_time_s {
            plan.speed_scale = (t / s.min_layer_time_s).clamp(floor, 1.0);
        }
    });
}

/// Time for an extrusion polyline, with junction-speed look-ahead. Both ends stop
/// (a retraction brackets every path).
fn polyline_time(pts: &[Point], closed: bool, v_nom: f64, accel: f64, jerk: f64) -> f64 {
    let n_pts = pts.len();
    let count = if closed { n_pts } else { n_pts.saturating_sub(1) };
    let mut dist: Vec<f64> = Vec::with_capacity(count);
    let mut dir: Vec<(f64, f64)> = Vec::with_capacity(count);
    for k in 0..count {
        let p0 = pts[k];
        let p1 = pts[(k + 1) % n_pts];
        let (dx, dy) = (p1.x_mm() - p0.x_mm(), p1.y_mm() - p0.y_mm());
        let d = (dx * dx + dy * dy).sqrt();
        if d < 1.0e-6 {
            continue;
        }
        dist.push(d);
        dir.push((dx / d, dy / d));
    }
    let n = dist.len();
    if n == 0 {
        return 0.0;
    }

    // Entry speed at each segment: start with the junction limit (full stop at
    // the first), where a sharper corner allows a lower speed.
    let mut entry = vec![v_nom; n];
    entry[0] = 0.0;
    for i in 1..n {
        let cos = (dir[i - 1].0 * dir[i].0 + dir[i - 1].1 * dir[i].1).clamp(-1.0, 1.0);
        let sin_half = ((1.0 - cos) * 0.5).max(0.0).sqrt();
        let vj = if sin_half < 1.0e-6 { v_nom } else { jerk / (2.0 * sin_half) };
        entry[i] = vj.min(v_nom);
    }
    // Reverse: cap so we can decelerate to the next entry over the move.
    for i in (0..n).rev() {
        let exit = if i + 1 < n { entry[i + 1] } else { 0.0 };
        entry[i] = entry[i].min((exit * exit + 2.0 * accel * dist[i]).sqrt());
    }
    // Forward: cap so it's reachable by accelerating from the previous entry.
    for i in 1..n {
        entry[i] = entry[i].min((entry[i - 1] * entry[i - 1] + 2.0 * accel * dist[i - 1]).sqrt());
    }

    let mut t = 0.0;
    for i in 0..n {
        let exit = if i + 1 < n { entry[i + 1] } else { 0.0 };
        t += trapezoid_time(dist[i], entry[i], exit, v_nom, accel);
    }
    t
}

/// Time for one move of `dist` mm from `v_entry` to `v_exit`, cruising up to
/// `v_cruise`, at acceleration `accel`.
fn trapezoid_time(dist: f64, v_entry: f64, v_exit: f64, v_cruise: f64, accel: f64) -> f64 {
    if dist <= 0.0 {
        return 0.0;
    }
    let vc = v_cruise.max(v_entry).max(v_exit);
    let d_acc = ((vc * vc - v_entry * v_entry) / (2.0 * accel)).max(0.0);
    let d_dec = ((vc * vc - v_exit * v_exit) / (2.0 * accel)).max(0.0);
    if d_acc + d_dec <= dist {
        let d_cruise = dist - d_acc - d_dec;
        (vc - v_entry) / accel + d_cruise / vc.max(1.0e-6) + (vc - v_exit) / accel
    } else {
        let v_peak = (((2.0 * accel * dist + v_entry * v_entry + v_exit * v_exit) * 0.5).max(0.0)).sqrt();
        let v_peak = v_peak.max(v_entry).max(v_exit).max(1.0e-6);
        (v_peak - v_entry) / accel + (v_peak - v_exit) / accel
    }
}

/// Format a duration like "1h 23m" / "12m 30s" / "45s".
pub fn format_duration(seconds: f64) -> String {
    let total = seconds.max(0.0).round() as u64;
    let (h, m, sec) = (total / 3600, (total % 3600) / 60, total % 60);
    if h > 0 {
        format!("{h}h {m:02}m")
    } else if m > 0 {
        format!("{m}m {sec:02}s")
    } else {
        format!("{sec}s")
    }
}

/// Deposited bead volume (mm³) for one path — honors variable widths,
/// per-path flow (brick, ironing), bridge flow, and the extrusion multiplier.
/// Shared by the filament estimate and the heat stats so the preview maps
/// can't disagree with the totals.
fn path_volume_mm3(path: &ToolPath, layer_height_mm: f64, s: &Settings) -> f64 {
    if let Some(ws) = &path.widths {
        let n_pts = path.points.len();
        let segs = if path.closed { n_pts } else { n_pts.saturating_sub(1) };
        let mut volume = 0.0;
        for k in 0..segs {
            let d = dist_mm(path.points[k], path.points[(k + 1) % n_pts]);
            let w = 0.5 * (ws[k] + ws[(k + 1) % n_pts]);
            volume += d
                * config::bead_area_mm2(w, layer_height_mm * path.height_scale)
                * flow_factor(path, s);
        }
        return volume;
    }
    let mut len = 0.0;
    for w in path.points.windows(2) {
        len += dist_mm(w[0], w[1]);
    }
    if path.closed && path.points.len() >= 2 {
        len += dist_mm(path.points[path.points.len() - 1], path.points[0]);
    }
    len * config::bead_area_mm2(path.width_mm, layer_height_mm * path.height_scale) * flow_factor(path, s)
}

/// Deposited bead volume (mm³) for one layer.
fn layer_volume_mm3(layer: &LayerPlan, s: &Settings) -> f64 {
    layer.paths.iter().map(|p| path_volume_mm3(p, layer.height_mm, s)).sum()
}

/// The thermal governor's per-path speed multiplier (1.0 when ungoverned).
fn path_scale(layer: &LayerPlan, i: usize) -> f64 {
    layer.path_speed_scale.get(i).copied().unwrap_or(1.0)
}

/// Extrusion-only seconds for one path at a total speed multiplier — the
/// trapezoid simulation the layer estimate uses, exposed so the thermal
/// governor budgets with the same numbers.
fn path_extrusion_seconds(layer: &LayerPlan, i: usize, s: &Settings, total_scale: f64) -> f64 {
    let path = &layer.paths[i];
    if path.points.len() < 2 {
        return 0.0;
    }
    let accel = accel_for(path.kind, layer.index, s).max(1.0);
    let v = feed_for(path, layer.index, layer.height_mm, layer_flow_cap_mm3_s(layer, s), s) / 60.0 * total_scale;
    polyline_time(&path.points, path.closed, v, accel, s.jerk_mm_s.max(0.1))
}

/// Estimate filament used: `(length_mm, grams)`. Honors per-path flow (brick,
/// ironing), bridge flow, and the global extrusion multiplier.
pub fn estimate_filament(layers: &[LayerPlan], s: &Settings) -> (f64, f64) {
    let volume: f64 = layers.iter().map(|l| layer_volume_mm3(l, s)).sum();
    let length_mm = volume / s.filament_area_mm2();
    let grams = volume / 1000.0 * s.filament_density_g_cm3; // 1000 mm³ = 1 cm³
    (length_mm, grams)
}

/// Per-layer numbers behind the preview heat maps.
pub struct LayerStats {
    /// Seconds printing this layer (its Z move + extrusion + travels).
    pub secs: f64,
    /// Thermal energy deposited (J): bead volume × density × cₚ × (nozzle − ambient).
    pub joules: f64,
    /// Solid footprint of the part at this Z (mm², net of holes) — the area
    /// the heat must spread over and shed through. Falls back to the deposited
    /// cross-section when a layer carries no outline.
    pub footprint_mm2: f64,
}

/// Specific heat of FDM thermoplastics, J/(g·K): PLA ≈ 1.9, PETG ≈ 1.3,
/// ABS ≈ 1.5. One mid value is fine while the heat map is relative; promote
/// to a filament field if absolute joules ever matter.
const CP_J_PER_G_K: f64 = 1.8;
/// Temperature the deposited bead cools toward (°C).
const AMBIENT_C: f64 = 25.0;

/// Time, deposited heat, and footprint per layer. Time mirrors
/// [`estimate_seconds`]'s per-layer terms and volume comes from the same bead
/// math as [`estimate_filament`], so the preview maps track what the totals
/// and M73 progress already report.
pub fn per_layer_stats(layers: &[LayerPlan], s: &Settings) -> Vec<LayerStats> {
    let travel_v = s.travel_speed_mm_s.max(1.0);
    let mut prev_z = 0.0;
    let mut out = Vec::with_capacity(layers.len());
    for layer in layers {
        let mut secs = (layer.print_z_mm - prev_z).abs() / travel_v;
        prev_z = layer.print_z_mm;
        secs += layer_print_seconds(layer, s, layer.speed_scale);

        let volume = layer_volume_mm3(layer, s);
        let nozzle_c = layer_nozzle_c(layer, s);
        let joules = volume * s.filament_density_g_cm3 * 1e-3 // g/cm³ → g/mm³
            * CP_J_PER_G_K
            * (nozzle_c as f64 - AMBIENT_C).max(0.0);

        let outline_area = layer.outline.net_area_mm2().abs();
        let footprint_mm2 = if outline_area > 1e-6 {
            outline_area
        } else {
            volume / layer.height_mm.max(1e-6)
        };
        out.push(LayerStats { secs, joules, footprint_mm2 });
    }
    out
}

/// One island's (connected region's) share of a layer's heat numbers.
pub struct IslandStats {
    /// Thermal energy deposited into this island (J).
    pub joules: f64,
    /// The island's solid footprint (mm², its outer contour minus its holes).
    pub footprint_mm2: f64,
}

/// Per-island refinement of [`per_layer_stats`]: which island every path
/// lands on, and each island's deposited heat and footprint. The cooling
/// window is *not* per island — a region keeps cooling while the nozzle works
/// elsewhere on the layer — so heat maps should divide island joules by the
/// **layer** seconds and the island footprint. That is exactly why a chimney
/// sharing layers with a hull is safe while a lone chimney overheats.
pub struct LayerIslands {
    /// Island index for every path (parallel to `LayerPlan::paths`).
    pub path_island: Vec<usize>,
    pub islands: Vec<IslandStats>,
}

/// Floor for an island's thermal footprint (mm²) — about a 3×3-bead pad.
/// True lone needles thinner than this are under-represented by the heat
/// model anyway (nozzle dwell dominates); min-layer-time owns that class.
const MIN_ISLAND_FOOTPRINT_MM2: f64 = 2.0;

pub fn per_layer_islands(layers: &[LayerPlan], s: &Settings) -> Vec<LayerIslands> {
    layers.iter().map(|layer| islands_of(layer, s)).collect()
}

/// Island split for one layer — see [`per_layer_islands`].
fn islands_of(layer: &LayerPlan, s: &Settings) -> LayerIslands {
    {
        {
            // CCW outer contours are the islands; CW holes subtract from the
            // outer that contains them.
            let outers: Vec<&Contour> =
                layer.outline.contours.iter().filter(|c| c.signed_area_mm2() > 0.0).collect();
            let mut islands: Vec<IslandStats> = outers
                .iter()
                .map(|c| IslandStats { joules: 0.0, footprint_mm2: c.signed_area_mm2() })
                .collect();
            for hole in layer.outline.contours.iter().filter(|c| c.signed_area_mm2() < 0.0) {
                if let Some(&p) = hole.points.first() {
                    if let Some(k) = outers.iter().position(|o| o.contains(p)) {
                        islands[k].footprint_mm2 =
                            (islands[k].footprint_mm2 + hole.signed_area_mm2()).max(1e-6);
                    }
                }
            }
            // No outline (degenerate layer) → one catch-all island sized by
            // the deposited cross-section, like per_layer_stats' fallback.
            if islands.is_empty() {
                islands.push(IslandStats {
                    joules: 0.0,
                    footprint_mm2: (layer_volume_mm3(layer, s) / layer.height_mm.max(1e-6)).max(1e-6),
                });
            }
            // Sub-bead slivers (the Benchy's 0.1 mm² towing-eye ring, deck
            // engravings) are not thermal islands: their heat conducts
            // laterally into the adjacent plastic within a couple of bead
            // widths, so a raw sub-mm² footprint would make the heat metric
            // meaninglessly huge. Floor the area at roughly a 3-bead pad.
            for isl in &mut islands {
                isl.footprint_mm2 = isl.footprint_mm2.max(MIN_ISLAND_FOOTPRINT_MM2);
            }
            let nozzle_c = layer_nozzle_c(layer, s);
            let j_per_mm3 = s.filament_density_g_cm3 * 1e-3 // g/cm³ → g/mm³
                * CP_J_PER_G_K
                * (nozzle_c as f64 - AMBIENT_C).max(0.0);
            let path_island: Vec<usize> = layer
                .paths
                .iter()
                .map(|path| {
                    // Walls and fills sit strictly inside their outline; skirt
                    // and brim (outside every outer) snap to the nearest one
                    // for coloring, but their heat lands on open bed far from
                    // the part — it must not count against any island.
                    let rep = path.points.first().copied();
                    let k = rep
                        .and_then(|p| outers.iter().position(|o| o.contains(p)))
                        .unwrap_or_else(|| nearest_outer(&outers, rep));
                    if path.kind != PathKind::Skirt {
                        islands[k].joules += path_volume_mm3(path, layer.height_mm, s) * j_per_mm3;
                    }
                    k
                })
                .collect();
            LayerIslands { path_island, islands }
        }
    }
}

/// Temperature shaping (v2, temp lever): bake a nozzle-temperature schedule
/// into the plan — cooler through chronically hot layer ranges, gently warmer
/// through cold bands — so deposition conditions even out toward the heat
/// target. Everything is decided *here, at slice time*, from the printer's
/// profiled ramp rates: ramps start early enough (backward anticipation pass)
/// that the nozzle arrives at each zone's temperature, and the emitted g-code
/// carries plain asynchronous `M104`s. There is no live feedback.
///
/// Honors the filament's printable window; cooled layers also derate the flow
/// ceiling (see [`layer_flow_cap_mm3_s`]). Temperature is a slow, global
/// actuator, so zones are layer *ranges* — the per-island speed governor
/// remains the fast spatial lever, and runs after this so it sees the shaped
/// energy and caps.
pub fn apply_temp_shaping(layers: &mut [LayerPlan], s: &Settings) {
    if !s.temp_shaping || layers.len() < 3 {
        return;
    }
    let base = s.nozzle_temp_c as f64;
    let tmin = (s.nozzle_temp_min_c as f64).min(base);
    let tmax = (s.nozzle_temp_max_c as f64).max(base);
    let swing = s.temp_shaping_swing_c.max(0.0);
    let target = s.governor_max_heat_mw_mm2 * 1e-3; // the thermal reference level
    if target <= 0.0 || swing <= 0.0 {
        return;
    }
    let n = layers.len();
    // 1. Raw demand from each layer's hottest island.
    let mut demand = vec![base; n];
    let mut secs = vec![0.05_f64; n];
    for (i, layer) in layers.iter().enumerate() {
        secs[i] = layer_print_seconds(layer, s, layer.speed_scale).max(0.05);
        if i == 0 {
            continue; // the first layer owns its own (adhesion) temperature
        }
        let li = islands_of(layer, s);
        let qmax = li
            .islands
            .iter()
            .filter(|isl| isl.joules > 0.0)
            .map(|isl| isl.joules / (secs[i] * isl.footprint_mm2.max(1e-9)))
            .fold(0.0_f64, f64::max);
        if qmax > target {
            // Hot: cool proportionally — the full swing at 2× over target.
            let sev = (qmax / target - 1.0).clamp(0.0, 1.0);
            demand[i] = (base - swing * sev).max(tmin);
        } else if qmax > 0.0 && qmax < 0.6 * target {
            // Cold band: warm gently toward even deposition (≤ 40% of swing).
            let sev = (1.0 - qmax / (0.6 * target)).clamp(0.0, 1.0);
            demand[i] = (base + 0.4 * swing * sev).min(tmax);
        }
    }
    // 2. Suppress zones the hotend can't meaningfully follow (< ~20 s): short
    //    runs of a new value adopt their predecessor's temperature.
    const MIN_ZONE_S: f64 = 20.0;
    let mut i = 1;
    while i < n {
        let mut j = i;
        while j < n && demand[j].round() == demand[i].round() {
            j += 1;
        }
        let dur: f64 = secs[i..j].iter().sum();
        if dur < MIN_ZONE_S && demand[i].round() != demand[i - 1].round() {
            let prev = demand[i - 1];
            for d in &mut demand[i..j] {
                *d = prev;
            }
        }
        i = j;
    }
    // 3. Anticipation (backward): to *arrive* at a zone's temperature, earlier
    //    layers must already be partway there — cooling is the slow direction,
    //    so cool zones pull a long lead. Then a forward pass re-anchors on the
    //    fixed first-layer temperature (leads that don't fit arrive late).
    let heat = s.heat_rate_c_s.max(0.1);
    let cool = s.cool_rate_c_s.max(0.05);
    for i in (0..n - 1).rev() {
        let reach_dn = cool * secs[i + 1];
        let reach_up = heat * secs[i + 1];
        demand[i] = demand[i].clamp(demand[i + 1] - reach_up, demand[i + 1] + reach_dn);
    }
    demand[0] = base; // never shape the first layer
    for i in 1..n {
        let reach_dn = cool * secs[i];
        let reach_up = heat * secs[i];
        demand[i] = demand[i].clamp(demand[i - 1] - reach_dn, demand[i - 1] + reach_up);
    }
    // 4. Quantize to whole °C and write the plan: the trajectory (for the
    //    energy model and flow caps) plus an M104 staircase at change points.
    let mut cur_cmd = base.round();
    for (i, layer) in layers.iter_mut().enumerate().skip(1) {
        let t = demand[i].round();
        layer.planned_temp_c = if (t - base).abs() >= 1.0 { Some(t) } else { None };
        if t != cur_cmd {
            layer.temp_command_c = Some(t);
            cur_cmd = t;
        }
    }
}

/// One contiguous shaped stretch, for the reports. `temp_c` is the range's
/// farthest-from-base temperature (the zone's plateau).
pub struct TempZone {
    pub first_layer: usize,
    pub last_layer: usize,
    pub temp_c: f64,
}

/// Where temperature shaping moved the nozzle — read back from the plan.
pub fn audit_temp_shaping(layers: &[LayerPlan], s: &Settings) -> Vec<TempZone> {
    let base = s.nozzle_temp_c as f64;
    let mut rows: Vec<TempZone> = Vec::new();
    for layer in layers {
        let Some(t) = layer.planned_temp_c else { continue };
        match rows.last_mut() {
            Some(r) if r.last_layer + 1 == layer.index => {
                r.last_layer = layer.index;
                if (t - base).abs() > (r.temp_c - base).abs() {
                    r.temp_c = t;
                }
            }
            _ => rows.push(TempZone {
                first_layer: layer.index,
                last_layer: layer.index,
                temp_c: t,
            }),
        }
    }
    rows
}

/// Thermal governor (v1, speed lever): for every island whose heat load —
/// deposited joules ÷ (layer seconds × island footprint) — exceeds the
/// target, scale that island's print speeds down until it fits. Slowing one
/// island lengthens the whole layer, which also cools the others, so islands
/// are handled worst-first against the updated layer time. Speeds never drop
/// below `min_print_speed_mm_s`; islands still hot at that floor are left
/// there and surface via [`audit_governor`] — slowing alone can't fix them.
/// Derived at slice time and stored only on the plan: toggling off returns
/// exactly the user's speeds.
pub fn apply_thermal_governor(layers: &mut [LayerPlan], s: &Settings) {
    if !s.thermal_governor || s.governor_max_heat_mw_mm2 <= 0.0 {
        return;
    }
    // Spiral vase is one continuous loop — per-island pacing can't apply
    // mid-loop; the min-layer-time slowdown already paces it.
    if s.spiral_vase {
        return;
    }
    let target = s.governor_max_heat_mw_mm2 * 1e-3; // mW/mm² → W/mm²
    let floor_v = s.min_print_speed_mm_s.max(1.0);
    for layer in layers.iter_mut() {
        let li = islands_of(layer, s);
        let n_isl = li.islands.len();
        if n_isl == 0 || layer.paths.is_empty() {
            continue;
        }
        // Nominal per-path speeds for the floor clamps.
        let v_nom: Vec<f64> = (0..layer.paths.len())
            .map(|i| {
                if layer.paths[i].points.len() < 2 {
                    return f64::INFINITY;
                }
                feed_for(&layer.paths[i], layer.index, layer.height_mm, layer_flow_cap_mm3_s(layer, s), s)
                    / 60.0
                    * layer.speed_scale
            })
            .collect();
        // Effective scale of path i under island factor `f`: the floor binds
        // per path, so one already-slow path (an arc overhang, say) never
        // blocks the island's fast paths from slowing — and paths already
        // under the floor simply stay where they are.
        let eff = |i: usize, f: f64| -> f64 { f.max((floor_v / v_nom[i]).min(1.0)) };
        // Exact (trapezoid) extrusion seconds of island k at factor f.
        let island_time = |k: usize, f: f64| -> f64 {
            li.path_island
                .iter()
                .enumerate()
                .filter(|&(_, &kk)| kk == k)
                .map(|(i, _)| path_extrusion_seconds(layer, i, s, layer.speed_scale * eff(i, f)))
                .sum::<f64>()
        };
        let mut t_ext: Vec<f64> = (0..n_isl).map(|k| island_time(k, 1.0)).collect();
        let mut t_layer = layer_print_seconds(layer, s, layer.speed_scale);
        let mut f = vec![1.0_f64; n_isl];
        // Worst-first: slowing one island lengthens the layer, cooling the rest.
        let q0: Vec<f64> = (0..n_isl)
            .map(|k| {
                li.islands[k].joules / (t_layer.max(1e-9) * li.islands[k].footprint_mm2.max(1e-9))
            })
            .collect();
        let mut order: Vec<usize> = (0..n_isl).collect();
        order.sort_by(|&a, &b| q0[b].partial_cmp(&q0[a]).unwrap_or(std::cmp::Ordering::Equal));
        for &k in &order {
            if li.islands[k].joules <= 0.0 {
                continue;
            }
            let area = li.islands[k].footprint_mm2.max(1e-9);
            if li.islands[k].joules / (t_layer.max(1e-9) * area) <= target * 1.001 {
                continue;
            }
            // The whole layer must take this long for island k to fit.
            let t_needed = li.islands[k].joules / (target * area);
            let t_others = t_layer - t_ext[k];
            if t_others + island_time(k, 0.0) < t_needed {
                // Hot even with every path at its floor: take the floor and
                // let the audit say so — slowing can't fix this island.
                f[k] = 0.0;
            } else {
                // Bisect the factor against the real trapezoid time — short,
                // accel-dominated moves don't gain time linearly, so a
                // first-order guess under-slows small islands.
                let (mut lo, mut hi) = (0.0_f64, 1.0_f64);
                for _ in 0..20 {
                    let mid = 0.5 * (lo + hi);
                    if t_others + island_time(k, mid) >= t_needed {
                        lo = mid; // slow enough — try faster
                    } else {
                        hi = mid;
                    }
                }
                f[k] = lo;
            }
            let grown = island_time(k, f[k]);
            t_layer = t_others + grown;
            t_ext[k] = grown;
        }
        if f.iter().any(|&fk| fk < 1.0) {
            let scales: Vec<f64> =
                li.path_island.iter().enumerate().map(|(i, &k)| eff(i, f[k]).min(1.0)).collect();
            if scales.iter().any(|&x| x < 0.999) {
                layer.path_speed_scale = scales;
            }
        }
    }
}

/// One contiguous run of governed layers, for the reports.
pub struct GovernorRow {
    pub first_layer: usize,
    pub last_layer: usize,
    /// The strongest slowdown in the range (0.38 = slowed to 38% speed).
    pub worst_scale: f64,
    /// Some island in the range is still over the target even at the
    /// min-print-speed floor — it needs cooling, not more slowing.
    pub floor_hit: bool,
}

/// Where the thermal governor intervened — read back from the plan the same
/// way the g-code is generated, so the report can't drift from reality.
pub fn audit_governor(layers: &[LayerPlan], s: &Settings) -> Vec<GovernorRow> {
    let target = s.governor_max_heat_mw_mm2 * 1e-3;
    let mut rows: Vec<GovernorRow> = Vec::new();
    for layer in layers {
        if layer.path_speed_scale.iter().all(|&fk| fk >= 0.999) {
            continue; // empty (ungoverned) vecs land here too
        }
        let worst = layer.path_speed_scale.iter().copied().fold(1.0, f64::min);
        // Post-governor heat check: anything still hot ran out of floor.
        let li = islands_of(layer, s);
        let t = layer_print_seconds(layer, s, layer.speed_scale);
        let floor = li.islands.iter().any(|isl| {
            isl.joules > 0.0
                && isl.joules / (t.max(1e-9) * isl.footprint_mm2.max(1e-9)) > target * 1.05
        });
        match rows.last_mut() {
            Some(r) if r.last_layer + 1 == layer.index => {
                r.last_layer = layer.index;
                r.worst_scale = r.worst_scale.min(worst);
                r.floor_hit |= floor;
            }
            _ => rows.push(GovernorRow {
                first_layer: layer.index,
                last_layer: layer.index,
                worst_scale: worst,
                floor_hit: floor,
            }),
        }
    }
    rows
}

/// Closest outer contour to `rep` (by first-point distance), or 0.
fn nearest_outer(outers: &[&Contour], rep: Option<Point>) -> usize {
    let Some(p) = rep else { return 0 };
    let mut best = 0;
    let mut best_d = f64::INFINITY;
    for (k, o) in outers.iter().enumerate() {
        if let Some(&q) = o.points.first() {
            let d = dist_mm(p, q);
            if d < best_d {
                best_d = d;
                best = k;
            }
        }
    }
    best
}

const MIN_TRAVEL_MM: f64 = 0.8;

fn path_end(p: &ToolPath) -> Point {
    if p.closed {
        p.points[0]
    } else {
        p.points[p.points.len() - 1]
    }
}

fn travel_crosses(outline: &Polygons, a: Point, b: Point) -> bool {
    for c in &outline.contours {
        let n = c.points.len();
        for i in 0..n {
            if segments_intersect(a, b, c.points[i], c.points[(i + 1) % n]) {
                return true;
            }
        }
    }
    false
}

/// Proper segment intersection (touching/collinear treated as no crossing — the
/// travel endpoints sit strictly inside the outline, so that's correct here).
fn segments_intersect(a: Point, b: Point, c: Point, d: Point) -> bool {
    let o1 = orient(a, b, c);
    let o2 = orient(a, b, d);
    let o3 = orient(c, d, a);
    let o4 = orient(c, d, b);
    o1 != 0 && o2 != 0 && o3 != 0 && o4 != 0 && (o1 > 0) != (o2 > 0) && (o3 > 0) != (o4 > 0)
}

fn orient(p: Point, q: Point, r: Point) -> i128 {
    ((q.x - p.x) as i128) * ((r.y - p.y) as i128) - ((q.y - p.y) as i128) * ((r.x - p.x) as i128)
}

/// Even-odd containment in a polygon-with-holes.
fn in_region(outline: &Polygons, p: Point) -> bool {
    let mut inside = false;
    for c in &outline.contours {
        if c.contains(p) {
            inside = !inside;
        }
    }
    inside
}

/// A segment is a valid in-region travel if its midpoint is inside the solid
/// region and it crosses no contour edge.
fn visible(outline: &Polygons, p: Point, q: Point) -> bool {
    if p == q {
        return true;
    }
    let mid = Point::new((p.x + q.x) / 2, (p.y + q.y) / 2);
    in_region(outline, mid) && !travel_crosses(outline, p, q)
}

/// Above this many outline vertices, skip the O(n²) diagonal precompute and
/// route along the boundary only (still inside the part, never through a hole).
const COMB_VERT_CAP: usize = 600;
/// Hard ceiling for routing at all (beyond this, fall back to retract).
const ROUTE_CAP: usize = 3000;

/// Per-layer visibility graph over the outline vertices, used to route combing
/// travels that would otherwise cross a wall.
struct CombGraph {
    verts: Vec<Point>,
    adj: Vec<Vec<(usize, f64)>>,
}

impl CombGraph {
    fn build(outline: &Polygons) -> Self {
        let mut verts: Vec<Point> = Vec::new();
        let mut edges: Vec<(usize, usize)> = Vec::new();
        for c in &outline.contours {
            let m = c.points.len();
            if m < 2 {
                continue;
            }
            let base = verts.len();
            verts.extend_from_slice(&c.points);
            for k in 0..m {
                edges.push((base + k, base + (k + 1) % m));
            }
        }
        let n = verts.len();
        let mut adj = vec![Vec::new(); n];
        // Boundary edges are always traversable (route can follow the wall).
        for &(i, j) in &edges {
            let w = dist_mm(verts[i], verts[j]);
            adj[i].push((j, w));
            adj[j].push((i, w));
        }
        // Visibility diagonals (skip the O(n²) pass on very complex layers).
        if n <= COMB_VERT_CAP {
            for i in 0..n {
                for j in (i + 1)..n {
                    if visible(outline, verts[i], verts[j]) {
                        let w = dist_mm(verts[i], verts[j]);
                        adj[i].push((j, w));
                        adj[j].push((i, w));
                    }
                }
            }
        }
        Self { verts, adj }
    }

    /// Shortest in-region route from `a` to `b`, as the points after `a`
    /// (intermediates + `b`), or None if unreachable.
    fn route(&self, outline: &Polygons, a: Point, b: Point) -> Option<Vec<Point>> {
        let n = self.verts.len();
        if n == 0 || n > ROUTE_CAP {
            return None;
        }
        let (ai, bi) = (n, n + 1);
        let total = n + 2;
        let mut adj = self.adj.clone();
        adj.push(Vec::new());
        adj.push(Vec::new());
        for (idx, p) in [(ai, a), (bi, b)] {
            for k in 0..n {
                if visible(outline, p, self.verts[k]) {
                    let w = dist_mm(p, self.verts[k]);
                    adj[idx].push((k, w));
                    adj[k].push((idx, w));
                }
            }
        }
        let mut dist = vec![f64::INFINITY; total];
        let mut prev = vec![usize::MAX; total];
        let mut done = vec![false; total];
        dist[ai] = 0.0;
        loop {
            let mut u = usize::MAX;
            let mut best = f64::INFINITY;
            for (k, &dk) in dist.iter().enumerate() {
                if !done[k] && dk < best {
                    best = dk;
                    u = k;
                }
            }
            if u == usize::MAX || u == bi {
                break;
            }
            done[u] = true;
            for &(v, w) in &adj[u] {
                if dist[u] + w < dist[v] {
                    dist[v] = dist[u] + w;
                    prev[v] = u;
                }
            }
        }
        if !dist[bi].is_finite() {
            return None;
        }
        let point = |idx: usize| {
            if idx == ai {
                a
            } else if idx == bi {
                b
            } else {
                self.verts[idx]
            }
        };
        let mut route = Vec::new();
        let mut cur = bi;
        while cur != usize::MAX {
            route.push(point(cur));
            cur = prev[cur];
        }
        route.reverse();
        route.remove(0); // drop `a` (already there)
        Some(route)
    }
}

/// Diagnostic over the planned travels: `(crossing_travels, combed,
/// fell_back_to_straight, straights_cutting_a_hole)`. A combed travel has a
/// multi-point route; a fallback is a single retracted/z-hopped hop.
pub fn audit_combing(layers: &[LayerPlan]) -> (usize, usize, usize, usize) {
    let (mut crossing, mut combed, mut fallback, mut fallback_hole) = (0, 0, 0, 0);
    for layer in layers {
        let mut last_pos: Option<Point> = None;
        for (i, path) in layer.paths.iter().enumerate() {
            if path.points.len() < 2 {
                continue;
            }
            let start = path.points[0];
            if let (Some(prev), Some(tr)) = (last_pos, layer.travels.get(i)) {
                if tr.points.len() > 1 {
                    crossing += 1;
                    combed += 1;
                } else if tr.retract {
                    crossing += 1;
                    fallback += 1;
                    if crosses_hole(&layer.outline, prev, start) {
                        fallback_hole += 1;
                    }
                }
            }
            last_pos = Some(path_end(path));
        }
    }
    (crossing, combed, fallback, fallback_hole)
}

fn crosses_hole(outline: &Polygons, a: Point, b: Point) -> bool {
    for c in &outline.contours {
        if c.is_ccw() {
            continue; // only holes (CW contours)
        }
        let n = c.points.len();
        for i in 0..n {
            if segments_intersect(a, b, c.points[i], c.points[(i + 1) % n]) {
                return true;
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::{fit_arc, ARC_MIN_PTS, AMBIENT_C, CP_J_PER_G_K};
    use crate::{
        audit_governor, estimate_filament, estimate_seconds, generate, per_layer_islands,
        per_layer_stats, to_gcode,
    };
    use config::Settings;

    #[test]
    fn arc_fit_curves_yes_corners_no() {
        // A densely-sampled circle fits one arc...
        let circle: Vec<(f64, f64)> = (0..64)
            .map(|k| {
                let a = std::f64::consts::TAU * k as f64 / 64.0;
                (10.0 * a.cos(), 10.0 * a.sin())
            })
            .collect();
        let fit = fit_arc(&circle, 0, 0.05).expect("dense circle is an arc");
        assert!(fit.0 + 1 >= ARC_MIN_PTS, "arc spans several points");
        assert!(fit.1.hypot(fit.2) < 0.2, "center near origin: ({}, {})", fit.1, fit.2);
        // ...but a square's (concyclic) corners must NOT be rounded into an arc.
        let square = [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0), (0.0, 0.0)];
        assert!(fit_arc(&square, 0, 0.05).is_none(), "square is straight, not an arc");
    }

    #[test]
    fn arc_fit_rejects_tangential_jitter() {
        // Points that double back along the same circle stay within tolerance
        // and keep a consistent polyline turn, but the swept angle is not
        // monotone: emitting an arc would squeeze the whole back-and-forth
        // bead into the short start→end angular gap (an over-extruded blob —
        // found as 5 moves commanding up to 84 mm³/s on a real Benchy export).
        let r = 6.0;
        let angs = [0.0f64, 0.06, 0.12, 0.06, 0.01, 0.08, 0.14];
        let wiggle: Vec<(f64, f64)> = angs.iter().map(|&a| (r * a.cos(), r * a.sin())).collect();
        match fit_arc(&wiggle, 0, 0.05) {
            None => {}
            Some((j, cx, cy, _)) => {
                // If a prefix fits, its emitted length must equal the polyline
                // length over the same points (monotone sweep — no folding).
                let run = &wiggle[0..=j];
                let poly: f64 = run.windows(2).map(|w| (w[0].0 - w[1].0).hypot(w[0].1 - w[1].1)).sum();
                let arc = super::arc_span_len(run, cx, cy);
                assert!((arc - poly).abs() < 0.05, "arc len {arc:.3} vs polyline {poly:.3}");
            }
        }
        // A full circle plus overlap must not wrap past 360°.
        let lap: Vec<(f64, f64)> = (0..80)
            .map(|k| {
                let a = std::f64::consts::TAU * k as f64 / 64.0; // 1.25 laps
                (10.0 * a.cos(), 10.0 * a.sin())
            })
            .collect();
        let (j, cx, cy, _) = fit_arc(&lap, 0, 0.05).expect("the first lap is a fine arc");
        let run = &lap[0..=j];
        let poly: f64 = run.windows(2).map(|w| (w[0].0 - w[1].0).hypot(w[0].1 - w[1].1)).sum();
        let arc = super::arc_span_len(run, cx, cy);
        assert!((arc - poly).abs() < 0.1, "wrapped arc: len {arc:.3} vs polyline {poly:.3}");
    }

    #[test]
    fn gcode_is_klipper_relative_with_retraction() {
        let m = mesh::Mesh::cube(20.0);
        let s = Settings::default();
        let g = to_gcode(&generate(&m, &s), &s);

        assert!(g.contains("M83"), "relative extrusion mode");
        // Acceleration follows the feature: gentle first layer, gentle outer
        // wall (auto = accel/2), the main limit for everything else.
        assert!(g.contains("M204 S1000"), "first-layer acceleration");
        assert!(g.contains("M204 S1500"), "outer-wall acceleration");
        assert!(g.contains("M204 S3000"), "main acceleration");
        // Feature annotations for g-code viewers and analysis tools.
        for t in [";TYPE:Outer wall", ";TYPE:Inner wall", ";TYPE:Solid infill", ";TYPE:Skirt"] {
            assert!(g.contains(t), "missing {t}");
        }
        assert!(g.contains("SQUARE_CORNER_VELOCITY=10.0"), "emits Klipper square corner velocity");
        assert!(g.contains("G28"), "homes (generic start template)");
        assert!(g.contains("M104 S200"), "nozzle temp substituted");
        assert!(g.contains("M140 S60"), "bed temp substituted");
        assert!(g.contains("M84"), "disables steppers (generic end template)");
        assert!(
            g.lines().any(|l| l.starts_with("G1 X") && l.contains(" E")),
            "has extruding moves"
        );
        assert!(g.lines().any(|l| l.starts_with("G1 E-")), "has retraction moves");
    }

    #[test]
    fn retract_wipes_back_over_the_printed_bead() {
        let m = mesh::Mesh::cube(20.0);
        let s = Settings::default(); // wipe_mm = 2.0
        let plans = generate(&m, &s);
        let g = to_gcode(&plans, &s);
        // Find a retract that is followed by moves before the unretract — the
        // wipe — and check the first wipe target lies on the printed cube
        // perimeter (x or y at the wall coordinate), not out in the open.
        let lines: Vec<&str> = g.lines().collect();
        let mut found = false;
        for w in lines.windows(3) {
            if w[0].starts_with("G1 E-") && w[1].starts_with("G0 X") && !w[1].contains('Z') {
                found = true;
                break;
            }
        }
        assert!(found, "no wipe move directly after a retraction");
        // And with wipe disabled those moves disappear: the file shrinks.
        let mut s2 = s.clone();
        s2.wipe_mm = 0.0;
        let g2 = to_gcode(&generate(&m, &s2), &s2);
        assert!(
            g.lines().count() > g2.lines().count(),
            "wipe must add moves ({} vs {})",
            g.lines().count(),
            g2.lines().count()
        );
    }

    #[test]
    fn placeholders_are_substituted() {
        let mut s = Settings::default();
        s.start_gcode = "PRINT_START EXTRUDER={nozzle_temp} BED={bed_temp}".into();
        s.nozzle_temp_c = 215;
        s.bed_temp_c = 65;
        let g = to_gcode(&generate(&mesh::Mesh::cube(10.0), &s), &s);
        assert!(g.contains("PRINT_START EXTRUDER=215 BED=65"), "macro substituted");
        assert!(!g.contains("{nozzle_temp}"), "no leftover placeholders");
    }

    #[test]
    fn first_layer_temp_drops_after_first_layer() {
        let m = mesh::Mesh::cube(10.0);
        let mut s = Settings::default();
        s.first_layer_nozzle_temp_c = 230;
        s.nozzle_temp_c = 210;
        let g = to_gcode(&generate(&m, &s), &s);
        let l0 = g.find("; LAYER 0 ").unwrap();
        let l1 = g.find("; LAYER 1 ").unwrap();
        assert!(g[..l0].contains("M104 S230"), "start g-code heats to the first-layer temp");
        assert!(!g[l0..l1].contains("M104"), "no temp change during the first layer");
        assert!(g[l1..].contains("M104 S210"), "drops to the printing temp at layer 2");

        // Equal temps (the auto default): no temp change at all between the
        // first layer and the end g-code's cooldown.
        s.first_layer_nozzle_temp_c = 210;
        let g = to_gcode(&generate(&m, &s), &s);
        let l0 = g.find("; LAYER 0 ").unwrap();
        let cooldown = g.rfind("M104 S0").unwrap();
        assert!(!g[l0..cooldown].contains("M104"), "no mid-print temp change");
    }

    #[test]
    fn aux_and_exhaust_fans_gated_and_emitted() {
        let m = mesh::Mesh::cube(10.0);
        let mut s = Settings::default();
        s.aux_fan_speed = 0.75;
        s.exhaust_fan_speed = 0.8;
        // Without the hardware flags the P-forms must never appear — vanilla
        // Klipper/Marlin would read them as the primary fan.
        let g = to_gcode(&generate(&m, &s), &s);
        assert!(!g.contains("M106 P"), "no P-fans without the hardware flags");

        s.has_aux_fan = true;
        s.has_exhaust_fan = true;
        let g = to_gcode(&generate(&m, &s), &s);
        let l0 = g.find("; LAYER 0 ").unwrap();
        let l1 = g.find("; LAYER 1 ").unwrap();
        assert!(g[..l0].contains("M106 P3 S204"), "exhaust on from the start");
        assert!(!g[l0..l1].contains("M106 P2 S191"), "aux respects fan-off layers");
        assert!(g[l1..].contains("M106 P2 S191"), "aux at duty past the first layer");
        assert!(g.rfind("M106 P2 S0").unwrap() > l1, "aux shut off at the end");
        assert!(g.rfind("M106 P3 S0").unwrap() > l1, "exhaust shut off at the end");
    }

    #[test]
    fn per_layer_stats_match_totals() {
        let m = mesh::Mesh::cube(20.0);
        let s = Settings::default();
        let layers = generate(&m, &s);
        let stats = per_layer_stats(&layers, &s);
        assert_eq!(stats.len(), layers.len());
        // Per-layer seconds sum to the total estimate (identical terms).
        let total: f64 = stats.iter().map(|st| st.secs).sum();
        let est = estimate_seconds(&layers, &s);
        assert!((total - est).abs() < est * 1e-9, "{total} vs {est}");
        // Mid-layer footprint is the cube's 20×20 cross-section.
        let mid = &stats[stats.len() / 2];
        assert!((mid.footprint_mm2 - 400.0).abs() < 40.0, "got {}", mid.footprint_mm2);
        // Energy tracks the filament estimate: grams × cₚ × ΔT (all layers
        // share one temp under default settings).
        let (_mm, grams) = estimate_filament(&layers, &s);
        let joules: f64 = stats.iter().map(|st| st.joules).sum();
        let expect = grams * CP_J_PER_G_K * (s.nozzle_temp_c as f64 - AMBIENT_C);
        assert!((joules - expect).abs() < expect * 1e-6, "{joules} vs {expect}");
    }

    #[test]
    fn per_island_stats_split_disjoint_parts() {
        // Two 10 mm cubes 20 mm apart: every layer carries two islands, each
        // with one cube's footprint and half the deposited heat.
        let c = mesh::Mesh::cube(10.0);
        let mut soup: Vec<[mesh::Vec3; 3]> = Vec::new();
        for i in 0..c.triangles.len() {
            let t = c.triangle(i);
            soup.push(t);
            soup.push(t.map(|v| [v[0] + 20.0, v[1], v[2]]));
        }
        let m = mesh::Mesh::from_triangle_soup(&soup);
        let s = Settings::default();
        let layers = generate(&m, &s);
        let isl = per_layer_islands(&layers, &s);
        let stats = per_layer_stats(&layers, &s);
        let mid = layers.len() / 2;
        assert_eq!(isl[mid].islands.len(), 2, "two separate bodies");
        for k in 0..2 {
            let a = isl[mid].islands[k].footprint_mm2;
            assert!((a - 100.0).abs() < 12.0, "island footprint {a}");
        }
        let (a, b) = (isl[mid].islands[0].joules, isl[mid].islands[1].joules);
        assert!((a - b).abs() < (a + b) * 0.05, "heat splits evenly: {a} vs {b}");
        let total = stats[mid].joules;
        assert!(((a + b) - total).abs() < total * 1e-6, "islands sum to the layer");
        assert_eq!(isl[mid].path_island.len(), layers[mid].paths.len());
    }

    #[test]
    fn thermal_governor_slows_hot_tower() {
        // A 5×5×30 mm tower: tiny island, quick layers → hot. Governed, its
        // layers must slow until the heat load fits (or the floor binds); off,
        // the plan is untouched.
        let c = mesh::Mesh::cube(5.0);
        let mut soup: Vec<[mesh::Vec3; 3]> = Vec::new();
        for i in 0..c.triangles.len() {
            let t = c.triangle(i);
            soup.push(t.map(|v| [v[0], v[1], v[2] * 6.0]));
        }
        let m = mesh::Mesh::from_triangle_soup(&soup);
        let mut s = Settings::default();
        s.min_layer_time_s = 0.0; // isolate the governor from the layer-time pacing
        let plain = generate(&m, &s);
        assert!(plain.iter().all(|l| l.path_speed_scale.is_empty()), "off = untouched");

        s.thermal_governor = true;
        s.governor_max_heat_mw_mm2 = 6.0;
        let governed = generate(&m, &s);
        let mid = governed.len() / 2;
        assert!(
            governed[mid].path_speed_scale.iter().any(|&f| f < 0.999),
            "tower layers slowed"
        );
        let rows = audit_governor(&governed, &s);
        assert!(!rows.is_empty(), "intervention reported");
        // Post-governor heat sits at/under the target, unless the row says the
        // min-speed floor bound first.
        let stats = per_layer_stats(&governed, &s);
        let isl = per_layer_islands(&governed, &s);
        let q = isl[mid].islands[0].joules
            / (stats[mid].secs.max(1e-9) * isl[mid].islands[0].footprint_mm2.max(1e-9));
        let floored = rows
            .iter()
            .any(|r| r.floor_hit && (r.first_layer..=r.last_layer).contains(&mid));
        assert!(q <= 6.0e-3 * 1.06 || floored, "governed heat {q} still over target");
        // Slowing costs time, and the estimator reports it honestly.
        assert!(estimate_seconds(&governed, &s) > estimate_seconds(&plain, &s));
    }

    #[test]
    fn temp_shaping_schedules_cool_zone_with_lead() {
        // The same hot 5×5×30 mm tower, shaped instead of governed: its layers
        // must plan a cooler nozzle (within the filament window), the M104
        // staircase must start at/before the zone, the g-code must carry the
        // schedule, and cooled layers must derate the flow ceiling.
        let c = mesh::Mesh::cube(5.0);
        let mut soup: Vec<[mesh::Vec3; 3]> = Vec::new();
        for i in 0..c.triangles.len() {
            let t = c.triangle(i);
            soup.push(t.map(|v| [v[0], v[1], v[2] * 6.0]));
        }
        let m = mesh::Mesh::from_triangle_soup(&soup);
        let mut s = Settings::default();
        s.min_layer_time_s = 0.0;
        s.temp_shaping = true;
        s.governor_max_heat_mw_mm2 = 6.0; // reference level the tower exceeds
        let layers = generate(&m, &s);
        let mid = layers.len() / 2;
        let planned = layers[mid].planned_temp_c.expect("hot tower gets a cooler plan");
        assert!(planned < s.nozzle_temp_c as f64, "cooler than base, got {planned}");
        assert!(planned >= s.nozzle_temp_min_c as f64, "inside the filament window");
        // The staircase starts no later than the first shaped layer (the lead).
        let first_shaped = layers.iter().position(|l| l.planned_temp_c.is_some()).unwrap();
        let first_cmd = layers.iter().position(|l| l.temp_command_c.is_some()).unwrap();
        assert!(first_cmd <= first_shaped, "command {first_cmd} after zone {first_shaped}");
        // Schedule is baked into the g-code, header included — no live feedback.
        let g = to_gcode(&layers, &s);
        assert!(g.contains("temp shaping: layers"), "header reports the zones");
        assert!(
            g.matches("M104 S").count() >= 2,
            "scheduled setpoints present in the body"
        );
        // Cooler layer ⇒ derated flow cap (default 0.3 mm³/s per °C).
        let drop = s.nozzle_temp_c as f64 - planned;
        let cap = super::layer_flow_cap_mm3_s(&layers[mid], &s);
        assert!(
            (cap - (s.max_volumetric_speed_mm3_s - 0.3 * drop)).abs() < 1e-9,
            "cap {cap} vs drop {drop}"
        );
    }

    #[test]
    fn time_estimate_is_sane() {
        let m = mesh::Mesh::cube(20.0);
        let s = Settings::default();
        let secs = estimate_seconds(&generate(&m, &s), &s);
        // A 20mm cube at these settings: minutes, not seconds or days.
        assert!(secs > 60.0 && secs < 86_400.0, "got {secs}s");
    }

    #[test]
    fn volumetric_clamp_slows_and_reports() {
        let m = mesh::Mesh::cube(20.0);
        let mut s = Settings::default();
        s.print_speed_mm_s = 300.0; // 300 × 0.45 × 0.2 = 27 mm³/s, over any PLA
        s.solid_speed_mm_s = 240.0;
        // Stadium bead 0.45 × 0.2 = 0.0814 mm² → cap = 9 / 0.0814 ≈ 110.5 mm/s.
        s.max_volumetric_speed_mm3_s = 9.0;
        let layers = generate(&m, &s);

        let cap = 9.0 / config::bead_area_mm2(0.45, 0.2);
        let clamps = crate::emit::audit_flow_clamps(&layers, &s);
        assert!(!clamps.is_empty(), "clamp should engage");
        for (_, nominal, clamped) in &clamps {
            assert!(clamped < nominal, "{clamped} should be below {nominal}");
            assert!((*clamped - cap).abs() < 1.0, "cap ≈ {cap:.1} mm/s, got {clamped}");
        }

        // The g-code announces it and actually uses the capped feed,
        // never the asked-for F18000.
        let g = to_gcode(&layers, &s);
        assert!(g.contains("; flow limit = 9.0 mm3/s"));
        assert!(
            g.contains(&format!("; flow-limited: infill 300 -> {cap:.0} mm/s")),
            "header reports the clamp"
        );
        assert!(!g.contains("F18000"), "unclamped feed must not appear");

        // And the time estimate reflects the slower reality. (The margin is
        // modest on a small cube: at 3000 mm/s² the head rarely reaches the
        // nominal 300 mm/s before a corner anyway.)
        let slow = estimate_seconds(&layers, &s);
        s.max_volumetric_speed_mm3_s = 0.0; // unlimited
        let layers_fast = generate(&m, &s);
        let fast = estimate_seconds(&layers_fast, &s);
        assert!(slow > fast * 1.02, "clamped print must take longer ({slow:.0}s vs {fast:.0}s)");
        assert!(crate::emit::audit_flow_clamps(&layers_fast, &s).is_empty(), "0 = unlimited");
    }

    #[test]
    fn default_speeds_are_not_clamped() {
        // The stock profile combos must not trigger the limiter (15 mm³/s vs
        // 50 mm/s × 0.45 × 0.2 = 4.5 mm³/s) — no behavior change by default.
        let m = mesh::Mesh::cube(10.0);
        let s = Settings::default();
        assert!(crate::emit::audit_flow_clamps(&generate(&m, &s), &s).is_empty());
    }

    #[test]
    fn gcode_has_progress_and_metadata() {
        let m = mesh::Mesh::cube(10.0);
        let s = Settings::default();
        let g = to_gcode(&generate(&m, &s), &s);
        assert!(g.contains("; estimated printing time = "), "metadata header");
        assert!(g.contains("; filament used [g] = "), "filament metadata");
        assert!(g.lines().any(|l| l.starts_with("M73 P0 ")), "progress at start");
        assert!(g.contains("M73 P100 R0"), "progress at end");
    }

    #[test]
    fn fan_and_pressure_advance_emitted() {
        let m = mesh::Mesh::cube(10.0);
        let mut s = Settings::default();
        s.fan_speed = 0.8; // 204/255
        s.fan_off_layers = 2;
        s.pressure_advance = 0.045;
        let g = to_gcode(&generate(&m, &s), &s);
        assert!(g.contains("SET_PRESSURE_ADVANCE ADVANCE=0.0450"), "PA emitted");
        assert!(g.contains("M106 S204"), "fan at 80% duty");
        // Fan must stay off until layer 2: no M106 between LAYER 0 and LAYER 2.
        let l0 = g.find("; LAYER 0 ").unwrap();
        let l2 = g.find("; LAYER 2 ").unwrap();
        assert!(!g[l0..l2].contains("M106"), "fan off for the first two layers");
        assert!(g[l2..].contains("M106 S204"), "fan on from layer 2");
    }

    #[test]
    fn spiral_vase_ramps_z_continuously() {
        let m = mesh::Mesh::cube(20.0);
        let mut s = Settings::default();
        s.spiral_vase = true;
        s.bottom_layers = 2;
        s.skirt_loops = 0;
        let layers = generate(&m, &s);
        let g = to_gcode(&layers, &s);
        // Above the bottom, extruding moves carry Z (G1 X.. Y.. Z.. E..).
        let spiral_moves = g
            .lines()
            .filter(|l| l.starts_with("G1 X") && l.contains(" Z") && l.contains(" E"))
            .count();
        assert!(spiral_moves > 100, "vase should extrude with rising Z, got {spiral_moves}");
        // Z never decreases over the spiral moves.
        let mut last_z = 0.0;
        for line in g.lines().filter(|l| l.starts_with("G1 X") && l.contains(" Z")) {
            let z: f64 = line
                .split_whitespace()
                .find_map(|t| t.strip_prefix('Z').and_then(|v| v.parse().ok()))
                .unwrap();
            assert!(z >= last_z - 1e-6, "vase Z must never drop: {z} after {last_z}");
            last_z = z;
        }
        // No retractions once the spiral starts (continuous extrusion) — only
        // the single end-of-print park retract is allowed.
        let spiral_start = g.find("; LAYER 3 ").unwrap();
        let tail = &g[spiral_start..g.find("M73 P100").unwrap()];
        assert!(tail.matches("G1 E-").count() <= 1, "no retractions inside the spiral");
    }
}
