//! Turn planned toolpaths into G-code.
//!
//! Extrusion math: the deposited bead approximates a `width × height`
//! rectangle, so for a move of length `L` the filament advance is
//! `E = L * width * height / filament_cross_section`.
//!
//! The start/end sequences are a generic Marlin profile and a deliberate
//! placeholder — real per-printer templates arrive with the config system (M2).

use config::Settings;
use gcode::GcodeBuilder;
use geo2d::Point;

use crate::plan::{LayerPlan, PathKind};

/// Emit complete G-code for a planned model.
pub fn to_gcode(layers: &[LayerPlan], s: &Settings) -> String {
    let mut g = GcodeBuilder::new();
    let area = s.filament_area_mm2();
    let travel_f = s.travel_speed_mm_s * 60.0;

    // ---- start g-code (generic Marlin — PLACEHOLDER, tune per printer) ----
    g.comment("generated by slicer (M1) - generic Marlin profile, tune per printer");
    g.comment(&format!(
        "layer_height={} line_width={} walls={} infill={}",
        s.layer_height_mm, s.line_width_mm, s.wall_count, s.infill_density
    ));
    g.set_bed_temp(s.bed_temp_c, false);
    g.set_nozzle_temp(s.nozzle_temp_c, false);
    g.set_bed_temp(s.bed_temp_c, true);
    g.set_nozzle_temp(s.nozzle_temp_c, true);
    g.raw("G21"); // millimeters
    g.raw("G90"); // absolute XYZ
    g.raw("M82"); // absolute extrusion
    g.raw("G28"); // home all axes
    g.reset_extruder();
    g.fan(0);

    for layer in layers {
        g.comment(&format!("LAYER {} z={:.3}", layer.index, layer.print_z_mm));
        if layer.index == 1 {
            g.fan(255); // part cooling on after the first layer
        }
        g.move_z(layer.print_z_mm, travel_f);

        for path in &layer.paths {
            if path.points.len() < 2 {
                continue;
            }
            let feed = feed_for(path.kind, layer.index, s);
            let coeff = path.width_mm * layer.height_mm / area;

            let start = path.points[0];
            g.travel(start.x_mm(), start.y_mm(), travel_f);

            let mut prev = start;
            for &p in &path.points[1..] {
                g.extrude(p.x_mm(), p.y_mm(), dist_mm(prev, p) * coeff, feed);
                prev = p;
            }
            if path.closed {
                g.extrude(start.x_mm(), start.y_mm(), dist_mm(prev, start) * coeff, feed);
            }
        }
    }

    // ---- end g-code ----
    g.set_nozzle_temp(0, false);
    g.set_bed_temp(0, false);
    g.fan(0);
    g.raw("G91"); // relative
    g.raw("G1 Z5 F600"); // lift
    g.raw("G90"); // absolute
    g.raw("M84"); // disable steppers

    g.finish()
}

/// Feed rate (mm/min) for a path: first layer is slow everywhere; otherwise the
/// external perimeter is slowed for surface quality.
fn feed_for(kind: PathKind, layer_index: usize, s: &Settings) -> f64 {
    if layer_index == 0 {
        return s.first_layer_speed_mm_s * 60.0;
    }
    match kind {
        PathKind::ExternalPerimeter => s.print_speed_mm_s * 0.5 * 60.0,
        PathKind::Perimeter => s.print_speed_mm_s * 60.0,
        PathKind::Infill => s.print_speed_mm_s * 60.0,
    }
}

fn dist_mm(a: Point, b: Point) -> f64 {
    let dx = a.x_mm() - b.x_mm();
    let dy = a.y_mm() - b.y_mm();
    (dx * dx + dy * dy).sqrt()
}

#[cfg(test)]
mod tests {
    use crate::{generate, to_gcode};
    use config::Settings;

    #[test]
    fn gcode_has_expected_structure() {
        let m = mesh::Mesh::cube(20.0);
        let s = Settings::default();
        let g = to_gcode(&generate(&m, &s), &s);

        assert!(g.contains("G28"), "homes");
        assert!(g.contains("M104 S200"), "sets nozzle temp");
        assert!(g.contains("M140 S60"), "sets bed temp");
        assert!(g.contains("M84"), "disables steppers at end");
        // Has extruding moves with an E value.
        assert!(g.lines().any(|l| l.starts_with("G1 X") && l.contains(" E")));
        // Extruder advances monotonically (absolute E grows).
        let mut last_e = 0.0;
        let mut saw_growth = false;
        for line in g.lines() {
            if let Some(idx) = line.find(" E") {
                if let Ok(e) = line[idx + 2..].split_whitespace().next().unwrap_or("").parse::<f64>() {
                    if e > last_e {
                        saw_growth = true;
                    }
                    last_e = e;
                }
            }
        }
        assert!(saw_growth, "absolute E should increase");
    }
}
