//! Turn planned toolpaths into G-code.
//!
//! Extrusion math: the deposited bead approximates a `width × height` rectangle,
//! so a move of length `L` advances the filament by
//! `E = L * width * height / filament_cross_section`.
//!
//! Output targets Klipper: relative extrusion (`M83`) and a retraction before
//! every travel between separate extrusions. The start/end g-code comes from the
//! printer profile (see `config`); `{placeholders}` are substituted here.

use config::Settings;
use gcode::GcodeBuilder;
use geo2d::Point;

use crate::plan::{LayerPlan, PathKind};

/// Emit complete G-code for a planned model.
pub fn to_gcode(layers: &[LayerPlan], s: &Settings) -> String {
    let mut g = GcodeBuilder::new();
    let area = s.filament_area_mm2();
    let travel_f = s.travel_speed_mm_s * 60.0;
    let retract_f = s.retract_speed_mm_s * 60.0;

    g.comment("generated by slicer");
    g.comment(&format!(
        "layer_h={} line_w={} walls={} top/bot={}/{} infill={} bed={}x{}",
        s.layer_height_mm,
        s.line_width_mm,
        s.wall_count,
        s.top_layers,
        s.bottom_layers,
        s.infill_density,
        s.bed_size_x_mm,
        s.bed_size_y_mm
    ));

    // Machine state we depend on, then the printer's start sequence (heating /
    // homing / PRINT_START macro).
    g.raw("G21"); // millimeters
    g.raw("G90"); // absolute XYZ
    g.raw("M83"); // relative extrusion (Klipper-recommended)
    emit_template(&mut g, &s.start_gcode, s);
    g.fan(0);

    for layer in layers {
        g.comment(&format!("LAYER {} z={:.3}", layer.index, layer.print_z_mm));
        if layer.index == 1 {
            g.fan(255); // part cooling on after the first layer
        }
        g.move_z(layer.print_z_mm, travel_f);

        let mut printed = false;
        for path in &layer.paths {
            if path.points.len() < 2 {
                continue;
            }
            let feed = feed_for(path.kind, layer.index, s);
            let coeff = path.width_mm * layer.height_mm / area;
            let start = path.points[0];

            let retract = printed && s.retract_len_mm > 0.0;
            if retract {
                g.retract(s.retract_len_mm, retract_f);
            }
            g.travel(start.x_mm(), start.y_mm(), travel_f);
            if retract {
                g.unretract(s.retract_len_mm, retract_f);
            }

            let mut prev = start;
            for &p in &path.points[1..] {
                g.extrude(p.x_mm(), p.y_mm(), dist_mm(prev, p) * coeff, feed);
                prev = p;
            }
            if path.closed {
                g.extrude(start.x_mm(), start.y_mm(), dist_mm(prev, start) * coeff, feed);
            }
            printed = true;
        }
    }

    if s.retract_len_mm > 0.0 {
        g.retract(s.retract_len_mm, retract_f);
    }
    emit_template(&mut g, &s.end_gcode, s);

    g.finish()
}

/// Substitute `{placeholders}` in a template and emit it line by line.
fn emit_template(g: &mut GcodeBuilder, template: &str, s: &Settings) {
    let text = substitute(template, s);
    for line in text.lines() {
        if !line.trim().is_empty() {
            g.raw(line.trim_end());
        }
    }
}

fn substitute(template: &str, s: &Settings) -> String {
    template
        .replace("{nozzle_temp}", &s.nozzle_temp_c.to_string())
        .replace("{bed_temp}", &s.bed_temp_c.to_string())
        .replace("{bed_x}", &format!("{:.3}", s.bed_size_x_mm))
        .replace("{bed_y}", &format!("{:.3}", s.bed_size_y_mm))
        .replace("{layer_height}", &format!("{:.3}", s.layer_height_mm))
        .replace("{first_layer_height}", &format!("{:.3}", s.layer_height_mm))
        .replace("{nozzle_diameter}", &format!("{:.3}", s.nozzle_diameter_mm))
}

/// Feed rate (mm/min): first layer slow everywhere; otherwise the external
/// perimeter is slowed for surface quality.
fn feed_for(kind: PathKind, layer_index: usize, s: &Settings) -> f64 {
    if layer_index == 0 {
        return s.first_layer_speed_mm_s * 60.0;
    }
    match kind {
        PathKind::ExternalPerimeter => s.print_speed_mm_s * 0.5 * 60.0,
        // Skirt is layer-0 only (handled above); listed for exhaustiveness.
        PathKind::Skirt | PathKind::Perimeter | PathKind::Solid | PathKind::Infill => {
            s.print_speed_mm_s * 60.0
        }
    }
}

fn dist_mm(a: Point, b: Point) -> f64 {
    let dx = a.x_mm() - b.x_mm();
    let dy = a.y_mm() - b.y_mm();
    (dx * dx + dy * dy).sqrt()
}

#[cfg(test)]
mod tests {
    use crate::{generate, to_gcode};
    use config::Settings;

    #[test]
    fn gcode_is_klipper_relative_with_retraction() {
        let m = mesh::Mesh::cube(20.0);
        let s = Settings::default();
        let g = to_gcode(&generate(&m, &s), &s);

        assert!(g.contains("M83"), "relative extrusion mode");
        assert!(g.contains("G28"), "homes (generic start template)");
        assert!(g.contains("M104 S200"), "nozzle temp substituted");
        assert!(g.contains("M140 S60"), "bed temp substituted");
        assert!(g.contains("M84"), "disables steppers (generic end template)");
        assert!(
            g.lines().any(|l| l.starts_with("G1 X") && l.contains(" E")),
            "has extruding moves"
        );
        assert!(g.lines().any(|l| l.starts_with("G1 E-")), "has retraction moves");
    }

    #[test]
    fn placeholders_are_substituted() {
        let mut s = Settings::default();
        s.start_gcode = "PRINT_START EXTRUDER={nozzle_temp} BED={bed_temp}".into();
        s.nozzle_temp_c = 215;
        s.bed_temp_c = 65;
        let g = to_gcode(&generate(&mesh::Mesh::cube(10.0), &s), &s);
        assert!(g.contains("PRINT_START EXTRUDER=215 BED=65"), "macro substituted");
        assert!(!g.contains("{nozzle_temp}"), "no leftover placeholders");
    }
}
